---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  path: ./kubernetes/main/applications/kyverno/kyverno/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno
      namespace: kyverno
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
  path: ./kubernetes/main/applications/kyverno/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
