---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.30.5-alpine@sha256:9f4c1ea3601e398656992f738af9f84faf7a6d68299b2deaf049580e5da0d37f
            env:
              TZ: America/Detroit
              SIGNUPS_ALLOWED: "false"
              SHOW_PASSWORD_HINT: "false"
              DOMAIN: https://vault.zynthovian.xyz
              ADMIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-secret
                    key: admin-token

    persistence:
      data:
        enabled: true
        existingClaim: vaultwarden
        globalMounts:
          - path: '/data'

    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/name: "Vaultwarden"
          gethomepage.dev/group: "Apps"
          gethomepage.dev/icon: vaultwarden.png
          gethomepage.dev/enabled: "true"
          external-dns.alpha.kubernetes.io/target: nginx.zynthovian.xyz
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
        tls:
          - hosts:
              - *host
