apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-restic-config
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vrXnEXWK9BmTcdysh8YtLM6Gpg==,iv:3i4u/Ox10UK0+zbZiKP5IhTI/kwT1j4HdKBgeuZ0rcM=,tag:uVRcnG2xD9OmvmMpdyS/JQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gf9NTR5I1ynObkD9u4YYYuMqlbw+6VLHg02bfnnU7eG+NXUbQWNC6eOdseyyW6u2QBRI66i2MKdl2M5Nurrg3Q==,iv:CxMXMAjegLJs5JMjEZQSmt/XQ9JrZisYzoksGk7YV8M=,tag:2W9QoSHVqqIrs3WQDZCFLA==,type:str]
    #ENC[AES256_GCM,data:CGJPBbDaD/kX+KHF0lzCNjF3+XWI3oJycNn4rman,iv:PdaPt2/rJaZx7QqDtRAWr1DFMFDfC+LGJ9WvygZmlbc=,tag:3m+4njSA0vnPXVzLccxxxg==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:SxxLq2WApBFc8OWBo441LcxKcPgEZV03rAiajnNwXgdiVH5J,iv:g/bIRwkr3fKPKMFwlUviQ11HvgDZOBze6BlJWzS72yE=,tag:NRslNeWoFnQwCjdNaFBYHw==,type:str]
    #ENC[AES256_GCM,data:lzcqba/dyeHPRos6dIkR8dq8lNXKqdmJ8sQCbnuWGNVaIi0UH1BswkQ=,iv:8pzwwpwEp1xr5zj9Xek412MgWLLIV4KAb52R2S5OIH0=,tag:7kLjhZYwr6DIQSFcCTK0Mw==,type:comment]
    #ENC[AES256_GCM,data:9DLm9SnF3rrBwxS4Y7+f28h+03D1r81jfn8uYS4rykya8lVl8CbRGT7fENo02gNIEF1+C7wspsXUeMc7TPhideS4lMRxJw==,iv:vFlxv4tksxvHG9vTbbNoLfF3jBh5XAnUHJByVjolVfI=,tag:xC0trLhLiQkaX7ukkOtGEw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PvVwBLWscPrPvggCUxv/xJndAzc=,iv:OZqVh5zFynI06JOKRyT+Mbd86/oYldOILfiey08yI54=,tag:xKH5/+5ZVI6+I+vTmCWB7g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gSATTfZJqdyKZI8gM1lBv/2QPTUnNJWCHsnrWEUkjtGkEKd9ABd7Jg==,iv:gK7upcm5bEHIPz8KhR12JW+QZKDyXRDG0g8UEeCcMPo=,tag:a/lobzSFWoQj10RBF5cSnQ==,type:str]
    CUSTOM_CA_CRT: ENC[AES256_GCM,data:nq607jZcMBgZdSSd7hGTcatJXfzfJc7rWXNiZ1xDNx8TBnHwKIuf+VR8lLUW0rpKRmtranCaLAwkJHN8Bt9bH8Hm1WSWZHIFUobDcYYT36wYvyNoWUtp4RFckOPWOhLtkjOoFKIA+9SrJMF+NllY1Hu525e9gcNDabQZaMantN+vZFfrCnjSZr8+cbNvxUho6XROEtunNDxioWOHALHYwwLfx3LgFph4XVCA545/M0uFRAacO3uFpoDpCaCeNK7kdgEvbF5qF/QIwLfmvqdbSx3RM8c5z3zWd2y4gZTl7K6OrDL4KMDU5hUc1nHUHJMNwtYym7HLeD265exXhVrZGj/Y5w0Mp2cvwY08MSuxkxz/K7V4I0nnyVtn/A4iPmw72mpERRwsrBVRZ0+7w/WxfxmkXYXo6M82pQRNBQScM+BipHC7c9JYJHANxGSeRlzrYvzLviRYFba0LY7Nrsi9KlpeB7ayt8wlKV1CfiGtm2xikB5YF91FyYLWioufMy1VACeGnDQx8ijP8l4kr9ElzUAV562oKF8YTq8+Cg9RT7hYl5L6nuCSy5Yz+Sevk+OjUAySrd5skahrQh7Sxexrr4hu2Hlub/5A8m+dSsXMbkKk6N3+9qAOWV5gxSefLajRCluWj5pTiu7SaiVnpKZFY6RGtkDxMphsVOQb5l9WY4axhCLr0z5ji0qZcRBKNzXQdKjcmscMmSlwe9HI1UWq15j8zqEF4lI3qMJPEaWM+T2mwmKp54i9BoJV7xTKV+liO73n+77IP7HdIqT2ghxHVKMKVFbZULQWiV6WeQUREe4r9rPWWWscSPByiN1p4UgLY2ENrZ7QxRBhzOJ+3SAYGKy5WWA3/y2bXoW8657mGI1jSyWP+YGJY7/7dS4pST6GG0GuMkL1qQP/4x1hwz7HGI6IQpjW+F7jEGijTYQaqIUQ0iF449doZSA=,iv:A623DkApyJ2UK71+1UbbtQEQeLUWG77ykKv0ROfei4Y=,tag:+SmvfusQtJxzw42ut/CK7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNDBXVGF4OXVnd1A1bU5a
            UUtwQ1RoOU9kY3A0SWw4OWpvdmt1OXZQY3hFCnpqYjl3WFA2eWJicTBwUG53bUl6
            STl6N0JwNloydGZ5UERLZ1RqcXpoWG8KLS0tIFVOcy9VWEFDMHNBWjh0cTczNndp
            Vk1DdU9hSjdXTTlhalJYLzZ3NG9scE0KhzcLrEqhAowwEOyiVekhgKbONHEDb7ze
            jPRpsS4nc4hXHcui98us3J0En5ZDkzaDSCQFfy/wREVVZGALiJPBrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T23:31:09Z"
    mac: ENC[AES256_GCM,data:Dg1STqkctYZy4v24oCCKsdLxNlvqt09Hh+4733l+JbLPmsj6DL5lh8oUFKLVxwpDvmdv0+40rxGdi+VreTlhJQo5R2BAt9Ou1BtYgMqmgBCy678jocxVF0gg5pnzk3lbjJ3+4VzYJLi73d2cZL42pHKMPdV0b3dhOiuIbac/J4o=,iv:JKW1kR4CTvpJDbhriV4zb/27c58qP+dr3PjgOQkYNws=,tag:eKdhSpvgtV6Fbvt3LZrHTw==,type:str]
    pgp:
        - created_at: "2023-09-01T17:33:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAXRs1eZ7dDhVNeX1pir2/2OlNDjwo9HGj/zsXL5faD1Ew
            SOpFK8a6kpKqNoq9KCmwz3RrxYm5JaexLIkUxyxkAGv+uRTjDnx+wgmafoaV4dMq
            0pUB8gkD+nDh/cYUNqhA1hgvdHnLWjlv2Q/2ILatoUrnhoN2tbvyeskwMc+Fo1cO
            lGVKWPN/jdv3o3H/DioRUVABWsSPiI84TEnDspOuCwTceC8R+ZqXYekfLjABXIYf
            Mq3dr4umV8DYc4paSgVY5w/Qc25z1kjytaWgdBAECl1rteFnGxlyp1c7bXGoOIzo
            ZGOnGrSmxw==
            =PkUO
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
