apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app loki
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/applications/observability/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
