---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/operators/cert-manager/cert-manager/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuers-cert-manager
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cluster-operators-cert-manager
  path: ./kubernetes/operators/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  interval: 30m
  retryInterval: 1m
  timeout: 3m
