---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pod-gateway-operator
  namespace: flux-system
spec:
  targetNamespace: pod-gateway
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/applications/pod-gateway/pod-gateway/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: pod-gateway
      namespace: pod-gateway
  interval: 30m
  retryInterval: 1m
  timeout: 5m
