---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  # --[ General Cluster Settings]
  CLUSTER_TIMEZONE: "America/Detroit"
  # --[ Cluster security context ]
  SECURITY_CONTEXT_RUN_AS_USER: "1009"
  SECURITY_CONTEXT_RUN_AS_GROUP: "1009"
  SECURITY_CONTEXT_FS_GROUP: "1009"
  # --[ Cluster network cidrs ]
  NET_NODE_CIDR: "172.20.0.0/25"
  NET_POD_CIDR: "10.42.0.0/16"
  NET_SVC_CIDR: "10.43.0.0/16"
  NET_EIP_CIDR: "172.21.0.0/16"
  # --[ Service LBIPs ]
  SVC_NGINX_ADDR: "172.21.0.0"
  SVC_SYNCTHING_ADDR: "172.21.0.1"
  SVC_SYSLOG_ADDR: "172.21.0.50"
  SVC_POD_GATEWAY_ADDR: "172.21.0.20"
