apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-superuser-secret
    namespace: cnpg
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:osha7cLt99k=,iv:J9SlM/4uHdqXYm/MGdfJ5xFDhxcX1J3rSViLOCya04A=,tag:wb0xUubRYC7A5INQsfDaqw==,type:str]
    password: ENC[AES256_GCM,data:QpOngexlaxFTm+b3IcbqmdiLrF+Du5UpeTMVD1NxDxKsQG9KUdC9Om13T6qAvps=,iv:5bSk31nvJ6RnMFnAI1fpJnI2XQAt2RTCsYKqcze/YjU=,tag:FYa8UClD/AbrUadhqN2ULg==,type:str]
    aws-access-key: ENC[AES256_GCM,data:uWNh4sexWx4SWC3pDTpw5FBTF4o=,iv:kzs6ktcC4l3uuDaC7PjcTgPXaW5ZHOKJD2WL/GDbZck=,tag:6Mmps9cKwthv3yCXa+/2mA==,type:str]
    aws-secret-key: ENC[AES256_GCM,data:LEm+9HqJDXWxmpJ/1tZX/+Q8I3hMRu+aZm9SjoAsGqZXzVot4qw24A==,iv:uYDQuBthRfdybF4+oME/nkKV48snLPH4xpcyGNc91x0=,tag:TnBLygwmBCDMuRoA9KAcnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVFFLYTZjZjdmVk9hTXY1
            VnpYQlVpR1hLcDdTSnJrdU1oVlhiSkEwOTFFClRxQTN1ckdtWGEybVU3dFhpY0xD
            dXFyNUJkTlphbVJyVzF0VkNiYzBHOU0KLS0tIFQwMFdHSmxZaDl0RHBTUHFMd1lW
            SFNyT3NMWWR6a1VscWxJMklKT3cvZTQKhGLSOUz/5Qwga89XqnLvcK4NzFl60ww7
            Xn7abL9IjTshkGV+TxH6fVZntHmv/4Ww9oK8u4mtBX+TEhD9oZbPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-19T19:20:02Z"
    mac: ENC[AES256_GCM,data:gYjGnSBPp29g/6GSXG62XCngcBCiVOOzXfOMRXAqAYnI/Umq/cxfOl3C/COYsBMvHQBFXXZ5YJCsYOfIu+YHepfi8tXVzcFrPgpa9tnV+W5+DXQiJxca35JZo0cD9kmWuI7FUQ9xKIOwmuJLEcGiJZPEh49BNXFwmOMrcaC0aWg=,iv:dv5kpM7tLVKJTFwA/v3AmKKEPCJ8EBD1hmLllOmhzCU=,tag:qiBGrwG+2B/uorNV01HC0w==,type:str]
    pgp:
        - created_at: "2023-11-19T19:20:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA4dkUC9O3kNmHgTxeX9ppC+cBJQWV+xmlWTPCRW+/hB0w
            6SLzyIUyH4vIhGdfKA9cAK8fqEyiUg8AQ9wmCulhRHsDStGRtIHExpKxjl5US6eq
            0pMB09Mwimeq7rlKEv6EOlSyP2SOBEHj9Pj6Hwyzqd1k3nievdonMrAhHqo4nSlk
            YRnRcBFxA7IklY2vc0BYKYX3cJbjN1QrB8kymsNd/KyOPtdfr5KafC2399OJtJT5
            JyV1PX5d/dxfmxRwbnbkeX5CszfV8RMY+1oDsyRUsVpWtdYLzWUbhH+dUzmeCPpV
            lWwNTL4=
            =h+tu
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
