---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
data:
  bookmarks.yaml: |
    - Development:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Social:
        - Hacker News:
            - abbr: HN
              href: https://news.ycombinator.com/
        - Knockout:
            - abbr: KN
              href: https://knockout.chat/
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
        - ProtonDB:
            - abbr: PDB
              href: https://www.protondb.com/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: "cluster"
  services.yaml: ""
  settings.yaml: |
    background:
      image: '/images/ea2c05c2f21d5a97e409dd0644c49deea55df80e.jpg'
      blur: sm
      opacity: 100
    theme: dark
  widgets.yaml: |
    #- kubernetes:
    #    cluster:
    #      show: true
    #      cpu: true
    #      memory: true
    #      showLabel: true
    #      label: "cluster"
    - search:
        provider: duckduckgo
        target: _blank
