---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    controllers:
      main:
        type: deployment

        containers:
          main:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: latest@sha256:fc0d6e8b469ea8756d7c5bc542eb5c89064b9c47c3fa85f19b70a695c65cb782
              pullPolicy: IfNotPresent

    #defaultPodOptions:
    #! This didnt work, the container was built to 'drop permissions'. :vomiting_face:
    #? I could just build my own derivative container which has this done during build
    #? https://github.com/gethomepage/homepage/blob/91120302757d3cae1b5f6138e3703165850639ab/docker-entrypoint.sh#L18C63-L18C63
    #  securityContext:
    #    runAsUser: 568
    #    runAsGroup: 568
    #    fsGroup: 568
    #    fsGroupChangePolicy: OnRootMismatch
    #    supplementalGroups: [10000]

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
            - *host

    persistence:
      images:
        enabled: true
        type: 'nfs'
        server: 'xenia.zynthovian.xyz'
        path: '/srv/media/Wallpaper'
        readOnly: true
        globalMounts:
          - path: '/app/public/images'
      config:
        enabled: true
        type: configMap
        name: homepage
        advancedMounts:
          main:
            main:
              - path: /app/config/bookmarks.yaml
                subPath: bookmarks.yaml
              - path: /app/config/docker.yaml
                subPath: docker.yaml
              - path: /app/config/kubernetes.yaml
                subPath: kubernetes.yaml
              - path: /app/config/services.yaml
                subPath: services.yaml
              - path: /app/config/settings.yaml
                subPath: settings.yaml
              - path: /app/config/widgets.yaml
                subPath: widgets.yaml

    serviceAccount:
      create: true
      name: homepage
