---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-operators-local-path-provisioner
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  path: ./kubernetes/operators/kube-system/local-path-provisioner/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: local-path-provisioner
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
