---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pod-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    DNSPolicy: ClusterFirst
    # -- Namespaces that might contain routed PODs and therefore
    # require a copy of the generated settings configmap.
    routed_namespaces:
      - default
    settings:
      VXLAN_ID: 43
      VPN_INTERFACE: "tun0"
      VPN_TRAFFIC_PORT: 2050
      VPN_BLOCK_OTHER_TRAFFIC: true
      NOT_ROUTED_TO_GATEWAY_CIDRS: &local_cidrs >-
        172.22.0.0/16 ${NET_POD_CIDR} ${NET_SVC_CIDR}
      VPN_LOCAL_CIDRS: *local_cidrs
    webhook:
      gatewayDefault: false
      gatewayAnnotation: vpn.home.arpa/tunnel
      gatewayAnnotationValue: ivpn
      gatewayLabel: vpn.home.arpa/tunnel
      gatewayLabelValue: ivpn
      namespaceSelector:
        type: custom
        custom:
          matchExpressions:
            - key: vpn.home.arpa/tunnel
              operator: In
              values: ['ivpn']
    service:
      vpn:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_POD_GATEWAY_ADDR}"
        ports:
          shadowsocks:
            enabled: true
            port: 8388
    addons:
      vpn:
        enabled: true
        type: gluetun
        networkPolicy:
          enabled: false
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
        env:
          - name: VPN_SERVICE_PROVIDER
            value: ivpn
          - name: VPN_TYPE
            value: openvpn
          - name: OPENVPN_ENDPOINT_PORT
            value: 2050
          # Do not interject firewall rules, pod-gateway applies it's own
          - name: FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT
            value: "off"
          - name: FIREWALL_DEBUG
            value: "on"
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: 172.22.0.0/16,${NET_POD_CIDR},${NET_SVC_CIDR}
          - name: SHADOWSOCKS
            value: "on"
          - name: DOT
            value: "off"
          - name: UPDATER_PERIOD
            value: '24h'
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: pod-gateway
                key: openvpn-username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pod-gateway
                key: openvpn-username
          - name: SERVER_COUNTRIES
            value: "Canada"
          - name: FIREWALL_VPN_INPUT_PORTS
            value: "42557"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      netshoot:
        enabled: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: pod-gateway
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: pod-gateway
              spec:
                template:
                  spec:
                    volumes:
                      - name: server-cache
                        emptyDir: {}
                    initContainers:
                      - name: gluetun-updater
                        image: >-
                          ghcr.io/qdm12/gluetun:v3.38.0@sha256:5522794f5cce6d84bc7f06b1e3a3b836ede9100c64aec94543cb503bb2ecb72f
                        args: [ "update", "-enduser", "-providers", "ivpn" ]
                        volumeMounts:
                          - mountPath: /gluetun
                            name: server-cache
                    containers:
                      - name: gluetun
                        volumeMounts:
                          - mountPath: /gluetun
                            name: server-cache