---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-operators-metrics-server
  namespace: flux-system
spec:
  path: ./kubernetes/operators/kube-system/metrics-server/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: metrics-server
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
