---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: amd64-server-7f97c6
spec:
  disks:
    EVO-970-2TiB:
      allowScheduling: true
      evictionRequested: false
      path: /var/mnt/longhorn
      storageReserved: 0
      tags: []