---
- Secrets Management:
    - OpenBao:
        href: https://xenia.zynthovian.xyz:8200
        description: >
            open source, community-driven secrets manager and
            fork of Vault managed by the Linux Foundation's OpenSSF
- Storage Management:
    - RustFS:
        href: https://xenia.zynthovian.xyz:9001
        description: Reliable distributed file system
- Network Management:
    - Gluetun:
        icon: gluetun.png
        widget:
            type: gluetun
            url: http://gluetun.network.svc.cluster.local:8000
            version: 2