---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/source.toolkit.fluxcd.io/gitrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.24
  ignore: |
    # exclude all
    /*
    # include helm chart
    !/deploy/chart/local-path-provisioner
