---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-system
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: kube-prometheus-stack
      app.kubernetes.io/instance: kube-prometheus-stack
secretGenerator:
  - name: alertmanager-config
    files:
      - alertmanager.yaml=./config/alertmanager.yaml
configurations:
  - kustomizeconfig.yaml