---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-longhorn
  namespace: flux-system
spec:
  path: ./kubernetes/operators/longhorn-system/longhorn/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn-operator
      namespace: longhorn-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m

