---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"


    controllers:
      main:
        enabled: true
        type: deployment
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: docker.io/syncthing/syncthing
              tag: 1.28.0@sha256:30b6a53436527edf31d791361d14b1f5119cc6882dbcf07822b618ee7a74e115
            env:
              PUID: 1000
              PGID: 1000
            probes:
              liveness: &httpProbe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8384
              readiness: *httpProbe
              startup: *httpProbe
            resources:
              requests:
                cpu: 0.2m
                memory: 100M
              limits:
                cpu: 1
                memory: 500M

    service:
      main:
        enabled: true
        controller: main
        primary: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_SYNCTHING_ADDR}"
        ports:
          http:
            enabled: true
            primary: true
            port: 8384
            protocol: HTTP
            appProtocol: http
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          transtcp:
            enabled: true
            port: 22000
            protocol: TCP
          transquic:
            enabled: true
            port: 22000
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: nginx-internal
        annotations:
          gethomepage.dev/name: "Syncthing"
          gethomepage.dev/group: "Apps"
          gethomepage.dev/icon: syncthing.png
          gethomepage.dev/enabled: "true"
          external-dns.alpha.kubernetes.io/target: nginx-internal.zynthovian.xyz
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: syncthing
        globalMounts:
          - path: /var/syncthing
            readOnly: false
