---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io//kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-issuers-cert-manager
  path: ./kubernetes/operators/nginx-system/nginx-ingress-controller/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: zynthovian-xyz
      namespace: nginx-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io//kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-nginx-internal
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-policies-kyverno
    - name: cluster-operators-nginx-certificates
  path: ./kubernetes/operators/nginx-system/nginx-ingress-controller/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: nginx-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
