---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:

    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.31.0-alpine@sha256:03e9a6605da82b4b4e8e00b6a58ce5434e9723a5c60025b305020420cbf6b4ab
            env:
              TZ: America/Detroit
              SIGNUPS_ALLOWED: "false"
              SHOW_PASSWORD_HINT: "false"
              DOMAIN: https://vault.zynthovian.xyz
              ADMIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-secret
                    key: admin-token

    persistence:
      data:
        enabled: true
        existingClaim: vaultwarden
        globalMounts:
          - path: '/data'

    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx-internal
        annotations:
          gethomepage.dev/name: "Vaultwarden"
          gethomepage.dev/group: "Apps"
          gethomepage.dev/icon: vaultwarden.png
          gethomepage.dev/enabled: "true"
          external-dns.alpha.kubernetes.io/target: nginx-internal.zynthovian.xyz
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
        tls:
          - hosts:
              - *host
