---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  namespace: default
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
