---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${job}
  namespace: ${ns}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: main
          image: docker.io/restic/restic:0.17.1
          args: ["snapshots"]
          envFrom:
            - secretRef:
                #name: ${app}-volsync-secret
                name: ${app}-restic-config
          resources: {}
          env:
            - name: RESTIC_CACERT
              value: /run/secrets/custom_ca
          volumeMounts:
            - name: custom-ca
              subPath: custom_ca
              mountPath: /run/secrets/custom_ca
      volumes:
        - name: custom-ca
          configMap:
            name: "personal-certificate-authority"
            items:
              - key: ca-cert-personal.pem
                path: custom_ca