---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &ksn nginx-certificates
  namespace: flux-system
spec:
  targetNamespace: web-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *ksn
  dependsOn:
    - name: cert-manager
  path: ./kubernetes/main/applications/web-system/nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &ksn nginx-internal
  namespace: flux-system
spec:
  targetNamespace: web-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *ksn
  dependsOn:
    - name: nginx-certificates
  path: ./kubernetes/main/applications/web-system/nginx/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
