---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: elliana
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: syncthing
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    image:
      repository: docker.io/syncthing/syncthing
      tag: 1.27.0
    env:
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: 8384
      supplimental:
        type: LoadBalancer
        #externalIPs: ["${SVC_SYNCTHING_ADDR}"]
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_SYNCTHING_ADDR}"
        ports:
          discovery:
            port: 21027
            protocol: UDP
            primary: true
          tcp-transfer:
            port: 22000
            protocol: TCP
          quic:
            port: 22000
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "Syncthing"
          hajimari.io/icon: mdi:folder-sync
          gethomepage.dev/name: "Syncthing"
          gethomepage.dev/group: "Apps"
          gethomepage.dev/icon: syncthing.png
          gethomepage.dev/enabled: "true"
          external-dns.alpha.kubernetes.io/target: nginx.zynthovian.xyz
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: syncthing
        mountPath: /var/syncthing
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 600Mi
        cpu: 500m

