---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  namespace: elliana
  labels:
    app.kubernetes.io/name: syncthing
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
