---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.5.5@sha256:7fdab000ef0f57a2434c04683d660301bdc0bf1302da04b55f890fb562e7b537
            env:
              TZ: America/New_York
              QBITTORRENT__PORT: &svport 80
              QBITTORRENT__BT_PORT: &btport 50413
              QBT_BitTorrent__Session__Port: *btport
            envFrom:
              - configMapRef:
                  name: qbittorrent-env
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      annotations:
        vpn.home.arpa/tunnel: "ivpn"
      labels:
        vpn.home.arpa/tunnel: "ivpn"
      securityContext: #}---------------------------
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
      dnsConfig: #}---------------------------
        nameservers:
          - "1.1.1.1"
          - "8.8.8.8"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local

    persistence:
      downloads:
        type: nfs
        server: xenia.int.zynthovian.xyz
        path: /srv/media/Downloads/qb
        globalMounts:
          - path: '/downloads'
      config:
        enabled: true
        existingClaim: qbittorrent-config

    service:
      main:
        labels:
          vpn.home.arpa/tunnel: 'ivpn'
        ports:
          http:
            port: *svport
      bittorrent:
        enabled: true
        controller: main
        type: LoadBalancer
        labels:
          vpn.home.arpa/tunnel: 'ivpn'
        ports:
          bittorrent:
            enabled: true
            port: *btport
            protocol: TCP
            targetPort: *btport
        externalTrafficPolicy: Cluster
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        tls:
          - hosts:
              - qb.zynthovian.xyz
        hosts:
          - host: qb.zynthovian.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
