---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./restic.sops.yaml
  - ./volsync.yaml
patchesJson6902:
  - target:
      group: core
      version: v1
      kind: Endpoints
      name: qbittorrent
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          name: vpn.home.arpa/ivpn
          value: "true"
