---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: qbittorrent
  namespace: default
spec:
  sourcePVC: qbittorrent-config
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: qbittorrent-restic-config
    storageClassName: ceph-filesystem
    cacheCapacity: 2Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
