---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-mikrotik
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: prometheus-system
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs: ["--config.file=/config/snmp.yaml"]
    extraConfigmapMounts:
      - name: &name mikrotik-snmp-configmap
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: *name
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      params:
        - name: crs328-a
          module: ["mikrotik"]
          target: 172.22.0.126
          auth: ["public_v1"]
      path: /snmp
      scrapeTimeout: 30s
      relabelings:
        - { sourceLabels: ["__param_target"], targetLabel: instance }
