# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-applications-sonarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-cnpg-cluster
    - name: cluster-operators-pod-gateway
    - name: cluster-operators-rook-ceph-cluster
  path: ./kubernetes/applications/default/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sonarr
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
