---
apiVersion: batch/v1
kind: Job
metadata:
  name: "list-${rsrc}-${ts}"
  namespace: "${namespace}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: list
          image: docker.io/restic/restic:0.16.2
          args: ["snapshots"]
          envFrom:
            - secretRef:
                name: "${rsrc}-restic-config"
#TODO   The data below should be templated and excluded if CUSTOM_CA_CRT is not in ${rsrc}-restic-config
          env:
            - name: RESTIC_CACERT
              value: /run/secrets/custom_ca
          volumeMounts:
            - name: custom-ca
              subPath: custom_ca
              mountPath: /run/secrets/custom_ca
      volumes:
        - name: custom-ca
          secret:
            secretName: "${rsrc}-restic-config"
            items:
              - key: CUSTOM_CA_CRT
                path: custom_ca
