---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${rsrc}-${claim}-${ts}"
  namespace: "${namespace}"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${rsrc}-restic-config"
    destinationPVC: "${claim}"
    copyMethod: Direct
    storageClassName: ceph-block
    previous: ${previous}
