# Used by
# `k8s/operators/nginx-system`
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 2h
  url: https://kubernetes.github.io/ingress-nginx
