---
kubernetes:
  children:
    master:
      hosts:
        amd64-server-b5915c.int.zynthovian.xyz:
          # StackPos: 0
          ansible_host: 172.22.0.10
        amd64-server-7f97c6.int.zynthovian.xyz:
          # StackPos: 1
          ansible_host: 172.22.0.11
        amd64-server-a2e7bb.int.zynthovian.xyz:
          # StackPos: 2
          ansible_host: 172.22.0.12
    worker:
      hosts:
        # Example
        # amd64-worker-{{ intfid }}.{{ fqdn }}: