# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
stringData:
    TOKEN: ENC[AES256_GCM,data:7PqNbh7bipBPUTrrFv3dng7LnhkW2d78H2O7RGtGJxJCosffHopGbA==,iv:ht1YGWwh8RjFS9i4Ki7rVNyrQ9uew8Kd6pvCwGni1jc=,tag:P+8HjuVMYm0ufp7hU72maw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSWYyTWI2QzM0U0N0YmlX
            dDdlRm41RFBiTmQ3aXFwdU1lZlNoM0t0VjJzClJEcHpLVHlVeGswSXpjb2N6VUxj
            WFdFRXZDa2xUaDE2d0FRU29VV0o1WWsKLS0tIFdBU3FKM3A3TGdHQnBWWU5kMjk0
            WGdoZzdaeDYrUmZGSS9wOGF2RWMrNlUKii0Xq9z2KpbRO2Vk2GFiQJPWGBQ1xRvh
            EW4nt7PMvK44CbSrjYz8Yn0r0dp9q6k5k3VWZ3Ufb2jQ+tOa2R+saQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-19T13:05:17Z"
    mac: ENC[AES256_GCM,data:duoeoGmQZOsK2CzNdhhz930HQ2LVoSs7p0v1f2p7SGrFpomE+C315uDMhfH9IFPTHcGX3FuK2g/+3RGxPf7IMklOTzm2bzVRYTcgGDz0VZfCqynK2BK3GFmMve67tBlP0VN/TxPRK46BQvRfQr4hAK2UYbictVUBtuKjHy0vfec=,iv:G44jKBnZtCloBYTCnlVbN//FpQKbehawidh04v+VAdU=,tag:SB5Zpah+jotj5dgGfntPUA==,type:str]
    pgp:
        - created_at: "2023-08-19T13:05:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA3ebeWSwZsXcbpf0JvVZ4xjturtRrmRk1IXhlTFxEDk0w
            NSyhexOir2vbztH0jY4dyubAufvQIhsHGxbZwagI7U39n6iMZDu1RvgVxJ5jH2dL
            0pYBgqhBNtvc0G3EM6QU17Q0pqLBGOApNj5qs/CQn8O8FzI9fauUj0Kskwww4NdS
            pnOY+CtIGgjZC42p/+YmtIsrt58tv1YKXXE5+Z6gnQhbQ8QjbBB4qmLfmYqDWvbc
            dKuCbxm7WmaOztln9RzGxXDQ/lzEcJzMecDeB/u/bD02ia/avM0vPAEgHUW/MMuJ
            jhPpGpJ9u/s=
            =Qo4f
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
