---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-flux-private
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/TkPegatron/homelab-k8sflux-private
  ref:
    branch: main
  secretRef:
    name: github-deploy-key-private
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-private
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux-config
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: cluster-flux-private
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
