---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-csi-addons-controller
  namespace: flux-system
spec:
  path: ./deploy/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-csi-addons
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  images:
    - name:  quay.io/csiaddons/k8s-controller
      newTag: v0.8.0
