apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-secret
    namespace: external-dns
type: Opaque
stringData:
    tsig-algorithm: ENC[AES256_GCM,data:Dg0M3kmoO3sSozM=,iv:B3ts/INV97SU7kwn1BkNoc9nfJe/DP8ceoMKkG7OG2A=,tag:C/TckkD6F+AerTe0lhjF8g==,type:str]
    tsig-secret: ENC[AES256_GCM,data:nY9M4ISfh9FUVUTALqT5hLedNLFPqbsPHj7BdBtqfiGcpechivgTSFg030M=,iv:ogfiQeBApEDEhUdZoejN7tLoDwli3byIzZ4xjMtMvU0=,tag:eTRJXqnfBB1x3Ox2Oq/VrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK0l0YUFVUDRVQ3E2aGpT
            WDlBRnR0Y1RqTVdMdHNkdzNySmZsMGhFcmpNCndoNkVQNWhkQlpLVm1mUnYwbXBx
            TFFzdmFNNXpNbTBDbEFZQW1KUkdzNTgKLS0tIFFOd2xwZ2hMK1dyZkxncGljS3U4
            OUtWTHpFRUxHakphZnFuMjJ3Qms2TUEKlvmTmkdIy7L/2XsRCKSVvoFHJY3BsyS0
            DPk7Q1OuDKVlN5vkueeMdHW+gqGvGQ/sYBhAPg/hayA2SoKge+YE2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-19T19:20:01Z"
    mac: ENC[AES256_GCM,data:uzX4MjNpm345rEi0EFM756Ys+7ysaNWwnNUjLpfUlfM6NthAlrH1n73aagUcSwF7OwWkCl5BlMKrikf2fCpaFRAnhb2EOWcNSVxFIY0dVt8CbfGwU0IhS4KhR2eDehhftqaOYjUFgPbbHRaeNUewQD4pnRXZ37CBbNsLFybPcMc=,iv:vpU2MZdZXBw3ruJS2cOMwbVrno8sNyZV6pq3NxDGVXs=,tag:e/iOQBqU4mXg9/nkkggTIA==,type:str]
    pgp:
        - created_at: "2023-11-19T19:20:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAxuy9t8szfylWVynbdqYXio7PTV7hqBqfQS6RBeXTAC4w
            2s7XgpBEZqndF0gpNtCJ4Uk4tZl4gHE6B+KD4ZAo1DqpU1qs3+vxN0iLZnRcq6GX
            0pYB5eqh+eptqoxaSk2uicTY+VijvX/H/CT6cwLaGW5EX1sXzTs/GpyZu/NlrCBo
            knqst+rHtYcT2oc4fwdIcfawD7w3gn9//sNMeQJlSw46Aay+shzB4oIqHImiGRY+
            jc/Gzl1+J+0dQgkwAAPCVjT/9rTbNFob4T6U1xu3WhKrUILtSpPckDCy5dqJweLV
            pG7YvEfelzM=
            =uJ7K
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
