---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: personal-certificate-authority
data:
  ca-cert-personal.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC9zCCAn6gAwIBAgIUP+m/ni51/ZkzdW8Y3GPJulrT/2kwCgYIKoZIzj0EAwMw
    eTEmMCQGA1UECgwdWnludGhvdmlhbiBJbnRlcnN0ZWxsYXIgVW5pb24xKDAmBgNV
    BAsMH0RpZ2l0YWwgSW5mcmFzdHJ1Y3R1cmUgU2VydmljZXMxJTAjBgNVBAMMHFJv
    b3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMjQwOTE2MDAwMDAwWhcNMzQw
    OTE4MDAwMDAwWjB5MSYwJAYDVQQKDB1aeW50aG92aWFuIEludGVyc3RlbGxhciBV
    bmlvbjEoMCYGA1UECwwfRGlnaXRhbCBJbmZyYXN0cnVjdHVyZSBTZXJ2aWNlczEl
    MCMGA1UEAwwcUm9vdCBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTB2MBAGByqGSM49
    AgEGBSuBBAAiA2IABNiyroVO4PiMV8iQBv2ER0Qb/RdsX5k3OmAtaH4pIhyLcXHe
    8MdzYdMmnKJKHCBH24cXUQPX1Hm8uq1afxt3yYIVJyzcXXef/3xz2Y0uSpXZrBoJ
    mNqbtCtD8pAL2Oq5G6OBxjCBwzAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUw
    AwEB/zAdBgNVHQ4EFgQU8ywVEcGb+Wz3akgNXLymh9gu474wHwYDVR0jBBgwFoAU
    8ywVEcGb+Wz3akgNXLymh9gu474wNAYHKwYBBAF6AQQpDCdFbGxpYW5hIFBlcnJ5
    IDxlbGxpYW5hLnBlcnJ5QGdtYWlsLmNvbT4wKgYHKwYBBAF6AgQfDB1Ib21lbGFi
    IENlcnRpZmljYXRlIEF1dGhvcml0eTAKBggqhkjOPQQDAwNnADBkAjA7ajmZIkDL
    lpWWCbeYajQax59Xuv96kqVLKEHGtBmX9C9t0SJdXTiYQgFrwWvI+7YCMAc4mku6
    YHUmHnwIv1aE1uDJgENEg+0JPHYzuV+dSn0RIEmoq8FvNmlf1Cqs1wzlZA==
    -----END CERTIFICATE-----
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: reflect-personal-certificate-authority
  annotations:
    policies.kyverno.io/subject: Reflect-CertAuthority
    policies.kyverno.io/description: |
      Reflect personal cert authority public key to all namespaces.
    policies.kyverno.io/category: reflectors
spec:
  background: true
  rules:
    - name: reflect-cert-authority
      match:
        any:
          - resources:
              kinds: ['Namespace']
              #names: ['elliana']
      generate:
        generateExisting: true
        apiVersion: v1
        clone:
          name: personal-certificate-authority
          namespace: default
        kind: ConfigMap
        name: personal-certificate-authority
        namespace: '{{ request.object.metadata.name }}'
        synchronize: true
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-ca-certs
  annotations:
    policies.kyverno.io/category: mutations
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy will mutate incoming pods to include a predefined certificate authority within its native trust chain.

        1) An initcontainer will be injected within the pod which runs `update-ca-certificates`
            The initcontainer will mount CA certs from a config map at /usr/local/share/ca-certificates/
            The initcontainer will copy it's /etc/ssl/certs/ directory into an emptyDir volume
        2) Containers within the pod will be modified to mount the emptyDir volume as /etc/ssl/certs/
        3) Applications which use the native certificate store will trust certificates signed by the defined cert authority
spec:
  rules:
    - name: kyverno-ca-initcontainer
      match:
        any:
          - resources:
              kinds: [ Pod ]
              selector:
                matchLabels:
                  domain-certs-map.cluster.arpa: 'true'
      mutate:
        patchStrategicMerge:
          spec:
            volumes:
              - name: kyverno-ca
                emptyDir: {}
              - name: kyverno-ca-map
                configMap:
                  name: personal-certificate-authority
            initContainers:
              - name: kyverno-inject-ca
                image: ghcr.io/tkpegatron/alpine:3.19.1
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "Updating CA Certificates"
                    update-ca-certificates
                    echo "Copying CA Bundle to volume"
                    cp -r /etc/ssl/certs/* /mnt
                    echo "Complete!"
                volumeMounts:
                  - name: kyverno-ca
                    mountPath: /mnt
                  - name: kyverno-ca-map
                    mountPath: /usr/local/share/ca-certificates/ca-cert-personal.pem
                    subPath: ca-cert-personal.pem
    - name: kyverno-ca-volumemounts
      match:
        any:
          - resources:
              kinds: [ Pod ]
              selector:
                matchLabels:
                  domain-certs-map.cluster.arpa: 'true'
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    volumeMounts:
                      - name: kyverno-ca
                        mountPath: /etc/ssl/certs/
                      - name: kyverno-ca-map
                        mountPath: /usr/local/share/ca-certificates/ca-cert-personal.pem
                        subPath: ca-cert-personal.pem
