---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-cpu-request-rook
  annotations:
    policies.kyverno.io/title: Remove CPU requests for Rook-Ceph
    policies.kyverno.io/category: Bad Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy removes memory requests from all Pods in the rook-ceph namespace.
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: remove-containers-cpu-requests
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["rook-ceph"]
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchesJson6902: |-
              - path: /spec/containers/{{elementIndex}}/resources/requests/cpu
                op: remove
    - name: remove-initcontainers-cpu-requests
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["rook-ceph"]
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      mutate:
        foreach:
          - list: "request.object.spec.initContainers"
            patchesJson6902: |-
              - path: /spec/initContainers/{{elementIndex}}/resources/requests/cpu
                op: remove
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-memory-request-rook
  annotations:
    policies.kyverno.io/title: Remove memory requests for Rook-Ceph
    policies.kyverno.io/category: Bad Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy removes memory requests from all Pods in the rook-ceph namespace.
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: remove-containers-memory-requests
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["rook-ceph"]
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchesJson6902: |-
              - path: /spec/containers/{{elementIndex}}/resources/requests/memory
                op: remove
    - name: remove-initcontainers-memory-requests
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["rook-ceph"]
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      mutate:
        foreach:
          - list: "request.object.spec.initContainers"
            patchesJson6902: |-
              - path: /spec/initContainers/{{elementIndex}}/resources/requests/memory
                op: remove
