---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-operators-pod-gateway
  namespace: flux-system
spec:
  path: ./kubernetes/operators/pod-gateway/pod-gateway/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: pod-gateway
      namespace: pod-gateway
  interval: 30m
  retryInterval: 1m
  timeout: 5m
