---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
spec:
  interval: 1h
  chart:
    spec:
      chart: pod-gateway
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/angelnu/pod-gateway
              tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2
          gluetun:
            enabled: true
            dependsOn: main
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: v3.41.3@sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027
            envFrom:
              - secretRef:
                  name: pod-gateway-vpn
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 175m
                memory: 192Mi
        pod:
          annotations:
            secret.reloader.stakater.com/reload: pod-gateway-vpn
      webhook:
        containers:
          main:
            image:
              repository: ghcr.io/angelnu/gateway-admision-controller
              tag: dev@sha256:17e9bc66f9ccaa004db53dd9e55247e2da37c6912a251c36b33fab3a283a8d42
    service:
      gluetun:
        controller: main
        ports:
          http:
            port: 8000
    networkpolicies:
      main:
        enabled: false
    routed_namespaces:
      - default
      - media
    settings:
      VXLAN_ID: 43
      VPN_INTERFACE: "wg0"
      VPN_TRAFFIC_PORT: 2050
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 172.22.0.0/16"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 172.22.0.0/16"
    webhook:
      gatewayDefault: false
      gatewayAnnotation: vpn.home.arpa/tunnel
      gatewayAnnotationValue: ivpn
      gatewayLabel: vpn.home.arpa/tunnel
      gatewayLabelValue: ivpn
      namespaceSelector:
        type: custom
        custom:
          matchExpressions:
            - key: vpn.home.arpa/tunnel
              operator: In
              values: ['ivpn']
    configMaps:
      gluetun-config:
        forceRename: gluetun-config
        data:
          post-rules.txt: |-
            iptables -A INPUT -p icmp -i eth0 -j ACCEPT
            iptables -A INPUT -p udp --dport 8472 -i eth0 -j ACCEPT
          auth_config.toml: |-
            [[roles]]
            name = "status"
            routes = ["GET /v1/publicip/ip", "GET /v1/vpn/status"]
            auth = "none"
    persistence:
      gluetun-config:
        type: configMap
        name: gluetun-config
        advancedMounts:
          main:
            gluetun:
              - path: /iptables/post-rules.txt
                subPath: post-rules.txt
              - path: /gluetun/auth/config.toml
                subPath: auth_config.toml
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: vpn-gateway-pod-gateway-main
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: vpn-gateway-pod-gateway-main
              spec:
                template:
                  spec:
                    containers:
                      - name: gluetun
                        lifecycle:
                          postStart:
                            exec:
                              command:
                                - /bin/sh
                                - -c
                                - |
                                  # Delete existing rules to avoid duplicates
                                  ip rule del table 51820 || true
                                  ip -6 rule del table 51820 || true