---
global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - alertname
      - namespace
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: "null" # quote
  - name: pushover
    pushover_configs:
      - html: true
        message: |-
          {{- range .Alerts }}
            {{- if ne .Annotations.description "" }}
              {{ .Annotations.description }}
            {{- else if ne .Annotations.summary "" }}
              {{ .Annotations.summary }}
            {{- else if ne .Annotations.message "" }}
              {{ .Annotations.message }}
            {{- else }}
              Alert description not available
            {{- end }}
            {{- if gt (len .Labels.SortedPairs) 0 }}
              <small>
              {{- range .Labels.SortedPairs }}
                <b>{{ .Name }}:</b> {{ .Value }}
              {{- end }}
              </small>
            {{- end }}
          {{- end }}
        priority: '{{ if eq .Status "firing" }}1{{ else }}0{{ end }}'
        send_resolved: true
        sound: gamelan
        title: '{{ .CommonLabels.alertname }} [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]'
        token: ${SECRET_ALERTMANAGER_PUSHOVER_TOKEN}
        url_title: View in Alertmanager
        user_key: ${SECRET_ALERTMANAGER_PUSHOVER_USER_KEY}
route:
  group_by:
    - alertname
    - job
  group_interval: 10m
  group_wait: 1m
  receiver: pushover
  repeat_interval: 12h
  routes:
    - matchers:
        # If I decide to use an uptime system,
        #  watchdog can be moved to a receiver for it
        - alertname =~ "InfoInhibitor|Watchdog"
      receiver: "null" # quote
    - continue: true
      matchers:
        - severity = "critical"
      receiver: pushover
