---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-local-path-provisioner
  path: ./kubernetes/operators/prometheus-system/prometheus-stack/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: prometheus-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
