---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-operators-rook-ceph
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-policies-kyverno
  path: ./k8s/operators/rook-ceph/rook-ceph/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-operator
      namespace: rook-ceph
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-operators-rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-rook-ceph
  path: ./k8s/operators/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  retryInterval: 1m
  timeout: 5m
