---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources:
  - ./helmrelease.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: kyverno-dashboard
    files:
      - kyverno-dashboard.json=https://raw.githubusercontent.com/kyverno/grafana-dashboard/master/grafana/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
