---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-node-feature-discovery
  namespace: flux-system
spec:
  path: ./kubernetes/operators/kube-system/node-feature-discovery/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
#---
#? No devices yet
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cluster-operators-node-feature-discovery-rules
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: cluster-apps-node-feature-discovery
#  path: ./kubernetes/operators/kube-system/node-feature-discovery/rules
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: cluster-flux-public
#  wait: true
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m