apiVersion: v1
kind: Secret
metadata:
    name: wikijs-postgres-init-environment
    namespace: default
stringData:
    #ENC[AES256_GCM,data:BdloOrC4zBPqh0CVjn4=,iv:811E3hA6ZZmTCngtGKdIqS10yhShk/aURG+piSIn+WI=,tag:fclfCJJKm1FeY8RALEdCVQ==,type:comment]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HylqTiHIOpagXP/fbcvpgHZLhuBVuFs/zqQl55k0TwFT8A==,iv:LAI73AbechleCfDUL0K8X4rrWqJsyGACIIPHuDVm/Qg=,tag:Ox+KuUV5zMDvUBrvts304Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:nkyvM7pM44uAw1R+OaGildcalltinwOAXuo=,iv:PFSFQPJYTU6su8vPwU2wKsSvFx4YIGb23zkagcXSLYs=,tag:CJyNSG/9D8vDk/vYghDPMQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2qk/Pa24,iv:CJbEMS3VyLa0JOMtfAWbty1GdccNRmF4Q6kZqaSjnO4=,tag:425HfiBlf37qeenBQ+o9mw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:wBWDDLv7,iv:6gvtNk71FIsRvHymjiYk+YxfbXgsXF0XZdF4DUNd4Xk=,tag:cLrCo3j8VOoDDByCLM64iQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B2IsblbSn4FsEkCj5SDLMdlg+HUY928Mpd0DC/RykdkEK41LF7b+YyNkrU0QipM=,iv:qorXvRc2cR2HyvTMjyugAiup2XlXTksjsS3gjmVBLvI=,tag:5dVAHm5m59V33ql/wqozOw==,type:str]
    #ENC[AES256_GCM,data:8/1io39PAeN1QdKVg6adhOZ5,iv:1FvUiKcI5ACkAZHKXPaApQYvk2hsoRuJ9+LbuwFFDDU=,tag:0TrZnXR9riGPFdQ/js6G/g==,type:comment]
    DB_HOST: ENC[AES256_GCM,data:4VNOsW5W/7rXyOvTFrQ/FD26k9xNCQ1vDfTO5nc4kwXcRQ==,iv:43XtfLEfjlk//ZG/UlE4oRrIR9JT3vjh0dzEkI7u02Q=,tag:DrZ2fM5JQza70yoh8Du51w==,type:str]
    DB_PASS: ENC[AES256_GCM,data:4m1BDdyewQ9hZbbMGzDrVw/OBuh+l0DXRsY=,iv:JPagwPeH42wYgcpcUNdlTVRpETTFTlV7fxEpj3VQBko=,tag:kOnG1S39F8Nc4Wb/EaEbsA==,type:str]
    DB_TYPE: ENC[AES256_GCM,data:s9AekzBbDTo=,iv:FAZxLITRFBHo52K+cxehWXZX8mRLx6hn1BipoNvr3t0=,tag:FQJPNjhAQm/5de96yUF3dg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:YaqT3/+H,iv:NqSzA5BmmDRk4kH9q8vIYgr6XkitU1j8c00EHVKjuqk=,tag:qrKPFJ2EKaUd2o8hovQiQw==,type:str]
    DB_USER: ENC[AES256_GCM,data:bPfZWPJv,iv:8sDQT1aC9smzGa1Ju6BCewPeNiR/SU6TGC4Fy74OW3g=,tag:IADIsW4PGdhI0q/wTD7bDQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:j7Q6UA==,iv:lpR0N4dghop3uQ3ZRkFxOMQ6CCsSpP+xrNlLmTVs96w=,tag:kRQklmbdbexpDNu+QkoLdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbzRBMFhDdnIyNk9qRWlY
            Q1B2eGU1UURnNzduM0V6ZFFidGVRQUxCQ1FjCnpiY28yRURFblpJcXY5eXFLSEZJ
            V1ZPbDhEUUd4MldIdDdJd0l4c0Zxc3MKLS0tIDVjcVE4RTUrS0VaWXQzN2tKKzBu
            TWVPdkdnWE9VNDI3WE5PaENNbGowc0EKvkRh9IpukONRNBKDtMsrdM+ZcX1+FoSC
            1A9XasNci4e5xdA48C+qU4A4sM/enAk23hS7rOlFRu76hBclRlBuuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T01:27:37Z"
    mac: ENC[AES256_GCM,data:oel7t3XhQaUMPHrnAyps2Mz0lJqDUq63gYAnv0kC4hx0w1QDnL/BWPq7NRuQNf3/XTnhLB+FCFvqs2mD5o+tsqQ8jLvTsFO+FhPq+l1iVZhfRweRJrl1C6cpVr+sCrRdYwSJj4iSIzMXKWLtZFig9KZJ7rmWlqgZE1sWw87bhDI=,iv:/iFPGJ9lXOR9MBVSoQlc4pwY9VRT0FaOGBeFM6pfUTU=,tag:4J1MXqGN6SWja5bykG+d3A==,type:str]
    pgp:
        - created_at: "2023-11-29T01:27:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdArJEvhGyk6tcv+Hj8B/9lS0FJcksD/QNM3iwjhKGDCDIw
            h/oKNlX4dwompiqaC7iWyvHzyt0zKHKiih+3BiiY2mI3k/lwQ5K9wff7BCcJn0EZ
            0pYBI7EzZxcMWk3i05C37ii3V/V7saIdPhcyQvb2ZGD8pgI+PgLDeWr3p6weeIs+
            sF2FY58JjDBqN/cgSVLfD0Xiem3AzbLJP/fZ9BhWZM2TysPMkS8kii4w+fjlaRSf
            +k91GwAPqadEEYglb0yRtQqZjL9c4qAvfZkrlnmNZCQHU47scLQPnS9iQVKW95YH
            zUVRpGej7lM=
            =5WSS
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
