---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-cnpg-cluster
  path: ./kubernetes/applications/monitoring/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: grafana
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
