---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.12-8
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  #! enableSuperUserAccess is insecure,
  #!   consider defining databases using api rather than initcontainers
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-superuser-secret
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      serverName: &currentCluster kubernetes-main-65a3c8b11f61
      destinationPath: s3://postgres-cluster/
      endpointURL: https://xenia.zynthovian.xyz:9090
      endpointCA:
        name: homelab-ca
        key: ca-cert
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-s3-secret
          key: aws-access-key
        secretAccessKey:
          name: cloudnative-pg-s3-secret
          key: aws-secret-key
