apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-superuser-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:awKHQ9xzxx8=,iv:GfYaeVg+9erEmOazxiB7NBEE0eokbnKhQ6aajx07zCQ=,tag:DtYlgMX/czlI0uSC5ohdZg==,type:str]
    password: ENC[AES256_GCM,data:AfLYa/HeHC9AZUimgJnlF+kuL3hT7Eq8j/K/gresXKvbIRZwz6/COGeIYG90yhg=,iv:7iLIPXAhW3Vo8jUgu0wcyNQXQR6wiaeqdefsu+62Vu0=,tag:eCDG38CfHmbHu0VXXq9koQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXc4V1JSUW9Qb3EzNGhT
            YVhnZHMyMFdGcnF0TTR5Y2RVcWkvci9sb3pJCjRyblA0Q05IVnlGSWJOdkFwejQx
            UUZ3dk4rVkY1TU9oUUZnRGtTWUw3NVkKLS0tICtleVRNWjFEK2Y1QVlpZ3RNTytN
            STNDR1dScHkvWmpEbHJpZllrNUR4ZEkKMVx7STCtw0fiC5XpIKDQ5RrpJLqTAHRZ
            zlJ21IMeW5aPBGoKlFPCIkyYQ3RZGNhUbtK422a5VXuJzP+YxI4H0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T16:40:10Z"
    mac: ENC[AES256_GCM,data:XqO/SKW47OUMwc22dNZ2Kaa7k8GDjMBK0CvzKq0DZz8eC/mHMz/3Lr/ElT4hN+Ncy/RbHe/JZ+X2knGuBnyeqztFYo9uzg0ua7TnaDFNP5g3dEqD1Ym0rXbSIv6mudqwAgVfEWOoLxt0HQUG3jvn0OLnBh98w7JWkxhX9KBsAbQ=,iv:HHpe8ddgBhjZrjX9TXaGTIC9WJK8oEW2vLZ4FwFKHt4=,tag:QZ4YBb2BqPw9y3mIZOP4kA==,type:str]
    pgp:
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA7CeEbQo1AQRZfvyYWQACLtzBsCKq3iELM8fByKD3riQw
            mZapwR0PZjfOW0X9ey75A73oirKq5N09FpmWUY++OBbMoGMFBabhPLlEeIeGpyAz
            0pYB30Ccd3hRD1YTU0svF6R52WpbI4GH26B6eea+kzpr9bUeeHKUPDaQ37Lsx1nz
            Jmxio1LKOo4NpuaPEpRZRQa5EH67rTjQb1RpcsFofEZrlUrs1gJxRF8MXR4gnLmc
            L9KXWfCaqw3FrhAf8BKBAho9TJJyMsiLxo6ZheBxSxCKt1yolEMsG3ap/lLK9153
            U474lXZWVAY=
            =xMzq
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtU8CQcxKBkwSAQdA3gj1Oesw6MxEoG+NZgx6Z0cBJtwZ0ctjpidV4Pfgdxcw
            MmpHkYCJXCgUxULtHYDgWO+cUp6onF4upR6Bp8w9V/Mih+/WkqDRLF7KlEYDk6iz
            0l4BmfVp2+w2i2iYY4c4+XBLXBFf6tW7eAdyKi98dZy3vfp3CbIzI5BPTCKj8TBS
            nCxlTEQVp/49ByUyfBM1v6pn59ELW0a45C5pQeRfYJvvLgCLkAN6bsbmwm3OLpF1
            =4s6+
            -----END PGP MESSAGE-----
          fp: 07EF252155A078987177E39C11A37ED357D49372
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-s3-secret
    namespace: cnpg
    labels:
        cnpg.io/reload: "true"
stringData:
    aws-access-key: ENC[AES256_GCM,data:WnLGSqXlWdwP8YVT3gjr7lt6UWU=,iv:hOzEO/blnpFthgYuxSJNK/8TJxOs3E248qeZXmqd3xE=,tag:a+DV6PWMnhxVb7da5zCxJQ==,type:str]
    aws-secret-key: ENC[AES256_GCM,data:GmgBvfXW3PUv70ZgMZ+C+JyndiNBzDXWG4TzH6UQjqjGnw3hYZG+Sw==,iv:ThMC2e+RvxiLwj4okwj4XSr6y0SlYzF1wd63VdyuSVI=,tag:13Q3/EtjPv7EnK9Oz2SHyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXc4V1JSUW9Qb3EzNGhT
            YVhnZHMyMFdGcnF0TTR5Y2RVcWkvci9sb3pJCjRyblA0Q05IVnlGSWJOdkFwejQx
            UUZ3dk4rVkY1TU9oUUZnRGtTWUw3NVkKLS0tICtleVRNWjFEK2Y1QVlpZ3RNTytN
            STNDR1dScHkvWmpEbHJpZllrNUR4ZEkKMVx7STCtw0fiC5XpIKDQ5RrpJLqTAHRZ
            zlJ21IMeW5aPBGoKlFPCIkyYQ3RZGNhUbtK422a5VXuJzP+YxI4H0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T16:40:10Z"
    mac: ENC[AES256_GCM,data:XqO/SKW47OUMwc22dNZ2Kaa7k8GDjMBK0CvzKq0DZz8eC/mHMz/3Lr/ElT4hN+Ncy/RbHe/JZ+X2knGuBnyeqztFYo9uzg0ua7TnaDFNP5g3dEqD1Ym0rXbSIv6mudqwAgVfEWOoLxt0HQUG3jvn0OLnBh98w7JWkxhX9KBsAbQ=,iv:HHpe8ddgBhjZrjX9TXaGTIC9WJK8oEW2vLZ4FwFKHt4=,tag:QZ4YBb2BqPw9y3mIZOP4kA==,type:str]
    pgp:
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA7CeEbQo1AQRZfvyYWQACLtzBsCKq3iELM8fByKD3riQw
            mZapwR0PZjfOW0X9ey75A73oirKq5N09FpmWUY++OBbMoGMFBabhPLlEeIeGpyAz
            0pYB30Ccd3hRD1YTU0svF6R52WpbI4GH26B6eea+kzpr9bUeeHKUPDaQ37Lsx1nz
            Jmxio1LKOo4NpuaPEpRZRQa5EH67rTjQb1RpcsFofEZrlUrs1gJxRF8MXR4gnLmc
            L9KXWfCaqw3FrhAf8BKBAho9TJJyMsiLxo6ZheBxSxCKt1yolEMsG3ap/lLK9153
            U474lXZWVAY=
            =xMzq
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtU8CQcxKBkwSAQdA3gj1Oesw6MxEoG+NZgx6Z0cBJtwZ0ctjpidV4Pfgdxcw
            MmpHkYCJXCgUxULtHYDgWO+cUp6onF4upR6Bp8w9V/Mih+/WkqDRLF7KlEYDk6iz
            0l4BmfVp2+w2i2iYY4c4+XBLXBFf6tW7eAdyKi98dZy3vfp3CbIzI5BPTCKj8TBS
            nCxlTEQVp/49ByUyfBM1v6pn59ELW0a45C5pQeRfYJvvLgCLkAN6bsbmwm3OLpF1
            =4s6+
            -----END PGP MESSAGE-----
          fp: 07EF252155A078987177E39C11A37ED357D49372
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: homelab-ca
    labels:
        cnpg.io/reload: "true"
stringData:
    ca-cert: ENC[AES256_GCM,data:ytjT+5G55hEpIAWZrFcW77YA0zUThXOpqqJg5y+a7bO5MAFR9dRZrGi2c/CzK0tdm+HVcp/BxhGO8dZpZhUy/KKvDx717ufYkZQtOs4v03JGavASWGm06EnI2v9AXKyuDcuNBxNmJG7P4btfaGbX03PadAU7hC7kFfbeBY1VjJ/BrPO6LWPYCywpJNyJ/gwcwA0n5AMHWM4efs7CIbzyPAfqC5y6eBq6yF47IzadO1Aw/16k7yzx+BsarPuCihXaVAELRawp6nt9HJkyijAgvx//uNn4taxsTiy4ZgpXZpzdq9i/C8ni2lwURoBNOTi2wF/k9h/XGK+heL9gfTO+8RW9dybkL7NZ07yZqHxPNS2wrIUHEbtO64jg9B4SUklrGthH/r9iefohSeQX7NDX23b8NICdOZoIc94BXV9Jx82TGIKZJitqdTwHb492CvjLSJezT4ml+UCLK+zpjwrg/ha57F7lCE+ePJV0AuOtPBZ3oQ2aS55pEfpLsIJ9abRBimzII+V1Z6S455jAuqgMBwqGlIwGvyh/o05b46gTa7LI/VkSRAHviFMJ/Tsv+oibinBusEfFoFUP8gaaSl7W8E8TOTXwk3uuJQeb2vvdL+75aBPOA2upNC/CQP/Pe0MWXrBvTPINLCYDDna75Pl2uh0Yv7jrNY4f4phK4dYJjvuAgzORSIadLYXsu5ba8qbMie86VNHCWBeQoIpvvHgNSaWV6lRZ/6JBga/E53UjXGuEF6zRhcLI4WMydSn+Rny6VL2UrinlDL/F/ngQ4DdrdHo1s2FromdFru4DnF4Noletc4miSOSpaIYYSmQszAKv1Rg9NPn5oA327Ao1BbjThJLi/RMwO8SVQrHdOWQQvBqE6/tdh8Ir0lqcc1pAELzhWkdVaZte//3H3qO+1vuAVPighp1kEpzdEGdKVgzsatSqzzUJ3g9JBNw=,iv:aP6Wup3BZAbOkXvd7IJYcI/baqL9voe+8qltegqMrZ0=,tag:W2vNTakO02kb8sdw9qu9Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXc4V1JSUW9Qb3EzNGhT
            YVhnZHMyMFdGcnF0TTR5Y2RVcWkvci9sb3pJCjRyblA0Q05IVnlGSWJOdkFwejQx
            UUZ3dk4rVkY1TU9oUUZnRGtTWUw3NVkKLS0tICtleVRNWjFEK2Y1QVlpZ3RNTytN
            STNDR1dScHkvWmpEbHJpZllrNUR4ZEkKMVx7STCtw0fiC5XpIKDQ5RrpJLqTAHRZ
            zlJ21IMeW5aPBGoKlFPCIkyYQ3RZGNhUbtK422a5VXuJzP+YxI4H0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T16:40:10Z"
    mac: ENC[AES256_GCM,data:XqO/SKW47OUMwc22dNZ2Kaa7k8GDjMBK0CvzKq0DZz8eC/mHMz/3Lr/ElT4hN+Ncy/RbHe/JZ+X2knGuBnyeqztFYo9uzg0ua7TnaDFNP5g3dEqD1Ym0rXbSIv6mudqwAgVfEWOoLxt0HQUG3jvn0OLnBh98w7JWkxhX9KBsAbQ=,iv:HHpe8ddgBhjZrjX9TXaGTIC9WJK8oEW2vLZ4FwFKHt4=,tag:QZ4YBb2BqPw9y3mIZOP4kA==,type:str]
    pgp:
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA7CeEbQo1AQRZfvyYWQACLtzBsCKq3iELM8fByKD3riQw
            mZapwR0PZjfOW0X9ey75A73oirKq5N09FpmWUY++OBbMoGMFBabhPLlEeIeGpyAz
            0pYB30Ccd3hRD1YTU0svF6R52WpbI4GH26B6eea+kzpr9bUeeHKUPDaQ37Lsx1nz
            Jmxio1LKOo4NpuaPEpRZRQa5EH67rTjQb1RpcsFofEZrlUrs1gJxRF8MXR4gnLmc
            L9KXWfCaqw3FrhAf8BKBAho9TJJyMsiLxo6ZheBxSxCKt1yolEMsG3ap/lLK9153
            U474lXZWVAY=
            =xMzq
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtU8CQcxKBkwSAQdA3gj1Oesw6MxEoG+NZgx6Z0cBJtwZ0ctjpidV4Pfgdxcw
            MmpHkYCJXCgUxULtHYDgWO+cUp6onF4upR6Bp8w9V/Mih+/WkqDRLF7KlEYDk6iz
            0l4BmfVp2+w2i2iYY4c4+XBLXBFf6tW7eAdyKi98dZy3vfp3CbIzI5BPTCKj8TBS
            nCxlTEQVp/49ByUyfBM1v6pn59ELW0a45C5pQeRfYJvvLgCLkAN6bsbmwm3OLpF1
            =4s6+
            -----END PGP MESSAGE-----
          fp: 07EF252155A078987177E39C11A37ED357D49372
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
