apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-superuser-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:osha7cLt99k=,iv:J9SlM/4uHdqXYm/MGdfJ5xFDhxcX1J3rSViLOCya04A=,tag:wb0xUubRYC7A5INQsfDaqw==,type:str]
    password: ENC[AES256_GCM,data:QpOngexlaxFTm+b3IcbqmdiLrF+Du5UpeTMVD1NxDxKsQG9KUdC9Om13T6qAvps=,iv:5bSk31nvJ6RnMFnAI1fpJnI2XQAt2RTCsYKqcze/YjU=,tag:FYa8UClD/AbrUadhqN2ULg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVFFLYTZjZjdmVk9hTXY1
            VnpYQlVpR1hLcDdTSnJrdU1oVlhiSkEwOTFFClRxQTN1ckdtWGEybVU3dFhpY0xD
            dXFyNUJkTlphbVJyVzF0VkNiYzBHOU0KLS0tIFQwMFdHSmxZaDl0RHBTUHFMd1lW
            SFNyT3NMWWR6a1VscWxJMklKT3cvZTQKhGLSOUz/5Qwga89XqnLvcK4NzFl60ww7
            Xn7abL9IjTshkGV+TxH6fVZntHmv/4Ww9oK8u4mtBX+TEhD9oZbPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T00:24:53Z"
    mac: ENC[AES256_GCM,data:pJCVYJqkym2eUNruEnyVdJMRvGvUR0Q1u+vEbn6DIgjE7+xTstnP6vZ4gBTVlVtpG5qZHuj/DCNASNCwC29bmyLfPTac4EeKoYhF7tJkcWrvTmoutTp4mFsgJSUxsb7QoMhfP4BPP4oJ6D89yL5fb3VGnAfX4oFxbUvoFFMOP74=,iv:XgOPvgSTBID22v838I4+vhEqvVG/yoO2nwfvOWz7lmg=,tag:M9jUvR5alCpAn46Ff4fhAg==,type:str]
    pgp:
        - created_at: "2023-11-19T19:20:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA4dkUC9O3kNmHgTxeX9ppC+cBJQWV+xmlWTPCRW+/hB0w
            6SLzyIUyH4vIhGdfKA9cAK8fqEyiUg8AQ9wmCulhRHsDStGRtIHExpKxjl5US6eq
            0pMB09Mwimeq7rlKEv6EOlSyP2SOBEHj9Pj6Hwyzqd1k3nievdonMrAhHqo4nSlk
            YRnRcBFxA7IklY2vc0BYKYX3cJbjN1QrB8kymsNd/KyOPtdfr5KafC2399OJtJT5
            JyV1PX5d/dxfmxRwbnbkeX5CszfV8RMY+1oDsyRUsVpWtdYLzWUbhH+dUzmeCPpV
            lWwNTL4=
            =h+tu
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-s3-secret
    namespace: cnpg
    labels:
        cnpg.io/reload: "true"
stringData:
    aws-access-key: ENC[AES256_GCM,data:uWNh4sexWx4SWC3pDTpw5FBTF4o=,iv:kzs6ktcC4l3uuDaC7PjcTgPXaW5ZHOKJD2WL/GDbZck=,tag:6Mmps9cKwthv3yCXa+/2mA==,type:str]
    aws-secret-key: ENC[AES256_GCM,data:LEm+9HqJDXWxmpJ/1tZX/+Q8I3hMRu+aZm9SjoAsGqZXzVot4qw24A==,iv:uYDQuBthRfdybF4+oME/nkKV48snLPH4xpcyGNc91x0=,tag:TnBLygwmBCDMuRoA9KAcnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVFFLYTZjZjdmVk9hTXY1
            VnpYQlVpR1hLcDdTSnJrdU1oVlhiSkEwOTFFClRxQTN1ckdtWGEybVU3dFhpY0xD
            dXFyNUJkTlphbVJyVzF0VkNiYzBHOU0KLS0tIFQwMFdHSmxZaDl0RHBTUHFMd1lW
            SFNyT3NMWWR6a1VscWxJMklKT3cvZTQKhGLSOUz/5Qwga89XqnLvcK4NzFl60ww7
            Xn7abL9IjTshkGV+TxH6fVZntHmv/4Ww9oK8u4mtBX+TEhD9oZbPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T00:24:53Z"
    mac: ENC[AES256_GCM,data:pJCVYJqkym2eUNruEnyVdJMRvGvUR0Q1u+vEbn6DIgjE7+xTstnP6vZ4gBTVlVtpG5qZHuj/DCNASNCwC29bmyLfPTac4EeKoYhF7tJkcWrvTmoutTp4mFsgJSUxsb7QoMhfP4BPP4oJ6D89yL5fb3VGnAfX4oFxbUvoFFMOP74=,iv:XgOPvgSTBID22v838I4+vhEqvVG/yoO2nwfvOWz7lmg=,tag:M9jUvR5alCpAn46Ff4fhAg==,type:str]
    pgp:
        - created_at: "2023-11-19T19:20:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA4dkUC9O3kNmHgTxeX9ppC+cBJQWV+xmlWTPCRW+/hB0w
            6SLzyIUyH4vIhGdfKA9cAK8fqEyiUg8AQ9wmCulhRHsDStGRtIHExpKxjl5US6eq
            0pMB09Mwimeq7rlKEv6EOlSyP2SOBEHj9Pj6Hwyzqd1k3nievdonMrAhHqo4nSlk
            YRnRcBFxA7IklY2vc0BYKYX3cJbjN1QrB8kymsNd/KyOPtdfr5KafC2399OJtJT5
            JyV1PX5d/dxfmxRwbnbkeX5CszfV8RMY+1oDsyRUsVpWtdYLzWUbhH+dUzmeCPpV
            lWwNTL4=
            =h+tu
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: homelab-ca
    labels:
        cnpg.io/reload: "true"
stringData:
    ca-cert: ENC[AES256_GCM,data:2BEbI4qC6gK+ACUT44sgIwqMFpWRVdexQjwV2Voo30QaQbrnQrPGnCxUudpZLhpA9t7IeVFxZVIFXZSjAIU5G/Ut3vZNRWt/nqw/rnlRg6qmy3BUj+4KnBFFgnb77ewxaG7j3t5UooMIDktq1sjNrzgMkRPNjfGBTLp1apUZUnczEaXfVJpN10odaxN5QwtlI3jN4D0v9W7FzHssdyqyb2JjVLNHeYRkw4/z/N5YOpH+Q0s92vy3R4BDIDrgSGiP3YDwFqyf4tX/NqqUvKoqwQnLln7m28Qo0Mxf2dy5MB8j+Fkk35pd2Oicy+puzIKZB3ugBrGIedsnKuV/MB6itNIhi4RWjZA2SbSNJ87DDuttBFxFqDoOD8haDgkhov02I39R6gaHQ8LdKff9fr3ne8pKqE05nB1yNLwaEJo5BeQakdYAYegc2BJtBlLNJwtkaCUYXEIASdZH88P41YzJRbZmuxIOrkqlAMVIQPVZiZ6RcD9KuWxR3sUZhBEBC8UCcM6r2E+C72OTbyR8KM2J+SSr1TM7W5T09jwyknqWOhU7sNLikodcNZjQGrUHx+/JW4EuoKLkkYNNRiuLATlUxnR2sf1+QU3s1ujB869V4sIFsaKEbUFspDTV0pKgLpCsy8Q0BX6JdPFNw2egQSK3HyIsP8p6RnC328FuCe+G3v0Zw1JRoHUETnaTPG2H1L+0CVUX417h4wKh8D20PLTH6JpaZqZ3RftE0B3dhAbgPYiERZTlEiaIkqsWzmM8YFAPnCeslwW97TvAVlQPNyyViu7Qhe79dtA+MGKsxrSvTxbFBjLgH+k3qHv1PdN/1AOYrk++vFwJ37VVVS0rY/3coN0Eiz0T3/WoQQsV1mjIPyvhI0D3CBaHJEmEYWVS9PYKwqWq4CKQ49b9AXNbrC4EbReHicjbgU/0Q7MvL9cs+BrZghA/ztRo8rg=,iv:IjLPlLClgqlaEbwS0t64eb8uMWKXe9WdSgo4OOGlw0w=,tag:MWnNQhqYAggvnKdfJJXljg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVFFLYTZjZjdmVk9hTXY1
            VnpYQlVpR1hLcDdTSnJrdU1oVlhiSkEwOTFFClRxQTN1ckdtWGEybVU3dFhpY0xD
            dXFyNUJkTlphbVJyVzF0VkNiYzBHOU0KLS0tIFQwMFdHSmxZaDl0RHBTUHFMd1lW
            SFNyT3NMWWR6a1VscWxJMklKT3cvZTQKhGLSOUz/5Qwga89XqnLvcK4NzFl60ww7
            Xn7abL9IjTshkGV+TxH6fVZntHmv/4Ww9oK8u4mtBX+TEhD9oZbPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T00:24:53Z"
    mac: ENC[AES256_GCM,data:pJCVYJqkym2eUNruEnyVdJMRvGvUR0Q1u+vEbn6DIgjE7+xTstnP6vZ4gBTVlVtpG5qZHuj/DCNASNCwC29bmyLfPTac4EeKoYhF7tJkcWrvTmoutTp4mFsgJSUxsb7QoMhfP4BPP4oJ6D89yL5fb3VGnAfX4oFxbUvoFFMOP74=,iv:XgOPvgSTBID22v838I4+vhEqvVG/yoO2nwfvOWz7lmg=,tag:M9jUvR5alCpAn46Ff4fhAg==,type:str]
    pgp:
        - created_at: "2023-11-19T19:20:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA4dkUC9O3kNmHgTxeX9ppC+cBJQWV+xmlWTPCRW+/hB0w
            6SLzyIUyH4vIhGdfKA9cAK8fqEyiUg8AQ9wmCulhRHsDStGRtIHExpKxjl5US6eq
            0pMB09Mwimeq7rlKEv6EOlSyP2SOBEHj9Pj6Hwyzqd1k3nievdonMrAhHqo4nSlk
            YRnRcBFxA7IklY2vc0BYKYX3cJbjN1QrB8kymsNd/KyOPtdfr5KafC2399OJtJT5
            JyV1PX5d/dxfmxRwbnbkeX5CszfV8RMY+1oDsyRUsVpWtdYLzWUbhH+dUzmeCPpV
            lWwNTL4=
            =h+tu
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
