---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sigstore
spec:
  interval: 15m
  url: https://sigstore.github.io/helm-charts
  timeout: 3m
