---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.3.1
  - name: kubernetes.core
    version: 5.2.0
  - name: community.sops
    version: 2.0.1
  - name: fedora.linux_system_roles
    version: 1.95.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.4
  - name: linux-system-roles.nbde_client
  - name: linux-system-roles.nbde_server
  - name: geerlingguy.node_exporter
  - name: arillso.logrotate