---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 9.2.0
  - name: kubernetes.core
    version: 5.0.0
  - name: community.sops
    version: 1.8.0
  - name: fedora.linux_system_roles
    version: 1.85.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.4
  - name: linux-system-roles.nbde_client
  - name: linux-system-roles.nbde_server
  - name: geerlingguy.node_exporter
  - name: arillso.logrotate