---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./delete-resource-limits.yaml
  - ./delete-resource-requests.yaml
  - ./mutate-ingress-annotations.yaml