---
- name: "Deprovision the kubernetes cluster"
  hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Uninstall k3s
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: uninstalled
    - name: Gather list of CNI files
      ansible.builtin.find:
        paths: /etc/cni/net.d
        patterns: "*"
        hidden: true
      register: directory_contents
    - name: Delete CNI files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ directory_contents.files }}"
