---
- name: "Provision the kubernetes cluster"
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:

    - name: Setup luks on /dev/sda
      changed_when: luks_rotate_shell.stdout == "changed"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
            printf "{{ luks_admin_password }}" > ./admin_passphrase
            cryptsetup luksFormat /dev/sda ./admin_passphrase
            cryptsetup luksAddKey \
              --key-file ./admin_passphrase \
              /dev/sda /etc/cryptokey.bin
            echo "rook_ssd /dev/sda /etc/cryptokey.bin discard"
            rm ./admin_passphrase
