---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chartRef:
    kind: OCIRepository
    name: homepage
  interval: 1h
  values:
    controllers:
      sonarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: main@sha256:fc699c09c620d4782f94fa9012be67364d9e3854add02e1e93bf76d808b6958c
            env:
              TZ: America/New_York
              HOMEPAGE_ALLOWED_HOSTS: "*"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthcheck
                    port: &port 3000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.zynthovian.xyz"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config-underlay:
        type: emptyDir
        globalMounts:
          - path: /app/config/
      config-overlay:
        type: configMap
        name: homepage
        globalMounts:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
          - path: /app/config/custom.css
            subPath: custom.css
          - path: /app/config/custom.js
            subPath: custom.js
          - path: /app/config/docker.yaml
            subPath: docker.yaml
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
          - path: /app/config/services.yaml
            subPath: services.yaml
          - path: /app/config/settings.yaml
            subPath: settings.yaml
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
      tmp:
        type: emptyDir
    rbac:
      roles:
        homepage:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - traefik.io
              resources:
                - ingressroutes
              verbs:
                - get
                - list
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - httproutes
                - gateways
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
      bindings:
        homepage:
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: homepage
          subjects:
            - kind: ServiceAccount
              name: homepage
              namespace: default