---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: homepage
    files:
      - bookmarks.yaml=./config/bookmarks.yml
      - custom.css=./config/custom.css
      - custom.js=./config/custom.js
      - docker.yaml=./config/docker.yml
      - kubernetes.yaml=./config/kubernetes.yml
      - services.yaml=./config/services.yml
      - settings.yaml=./config/settings.yml
      - widgets.yaml=./config/widgets.yml
generatorOptions:
  disableNameSuffixHash: true