---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync
  namespace: flux-system
spec:
  targetNamespace: volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/applications/volsync-system/volsync/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  interval: 30m
  retryInterval: 1m
  timeout: 5m
