---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/applications/kube-system/cilium/operator
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium-config
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cilium
  path: ./kubernetes/main/applications/kube-system/cilium/configuration
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app cilium-policy
#   namespace: flux-system
# spec:
#   targetNamespace: kube-system
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: cilium
#   path: ./kubernetes/main/applications/kube-system/cilium/policy
#   prune: false # never should be deleted
#   sourceRef:
#     kind: GitRepository
#     name: cluster-flux-public
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
