# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
stringData:
    TOKEN: ENC[AES256_GCM,data:sfkYgOaTIkwSXch0XAdQoDLvfbP/PCTG2wq4URQjrNhC33wSf9LWGA==,iv:1cJEmMVZ7CrXRjYW48Cxws6SJMBoE4teFYidNBFnPyE=,tag:Qe//wOZFHoEk3P64cgM0Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYVBMaEh2VkNVZmhzQVFF
            aFA2R3pGRThoaktBK0VQMUtyRkIzbll3MVVrCjVubzBmOGs5M1hnTzFYeWxvTnB2
            ckxMckZEbzFSQXNuK2Q0USsxUGpMVkkKLS0tIDdoYUpUNlhDUW14MVRJVlJDamNr
            d0tabE1Ja2dpdXRWT3BmekJUZ1E2S2MKkZIY3FZcJUyS3exrhVUW3Y+FOylWhsxU
            S8F540qHaA8RT9DBt4cAVLSe41lYSiEU0wUwjq3uyp5c903fJwFOYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T17:24:46Z"
    mac: ENC[AES256_GCM,data:ejr0zuBqpPZZjE3yeYFaInWd+KY99BDQNnOzE6wq0X/QA60Oi5cvAr4bHCB8u619gzZ+waa4j4f6UYKKLg6AA5vG+BK6qgJlPxZnorTdz4lMlhHinc60uXyaVgvO/Apbi+sxg9nFGgU5qtbhLA8HtY1OOkTRe/4E7XY7o4cPUI0=,iv:u924LHizRGVbVPQCXmk0RwXcoZ4JT+Og0rPs7iOCI5A=,tag:oYT7mrXqOO6NQNsnIgP6Mw==,type:str]
    pgp:
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdADlHWXorP/cXLc2PWyg254OkFIOS9bGL0RclN5zzyVyAw
            ZK0nqFyYEn2ixpWGSmcbzZwPF0h66v3Zb2r3rOP2jBI9XyKo+b7o5MW5LtTSj2dn
            0pUBb+W3gHBtn3R6DwzVsduHqrzAcoOWLACRKqGtuODsRiLTfYCyERRzC7+F5+/A
            u+QxN0iHIM0OaD1C/jiQpgxDZWvj8hug0KMUgfgNKIbZ65ORry2PsqFlWJrPOx1V
            rA6QaGeXuhRqWMBGCzhWV71+IPOO46m+YdUwe3hHo7qnZl5OIUcVYpH+RCwWf8rY
            RANH8CtEwQ==
            =c49L
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtU8CQcxKBkwSAQdAEcDDjtR/M+3QiHa0zxmG4sujCfc/1z6k8YEdi1GHCUkw
            MumMizXxLG30P+uzY8qRRnBfM2H7eAua5Fd1Ue0jy49oq3uoBTuSqNDltKMbm1MV
            0l4BjtvKOsWhMsDeqLeBwfviyfLzY52s75wWmCVQdGBvyypGAWGCPiHnjUKRE/zj
            GDpKFy3nnqlLjE84zBp9uIQT5rGgG1mhDBVJ1h2TZDSx4a+ejIHyHSPMNDpTgsEr
            =H+B/
            -----END PGP MESSAGE-----
          fp: 07EF252155A078987177E39C11A37ED357D49372
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
