---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ./namespace.yaml
  - ./network-policy.yaml
  # Flux Kustomizations
  - ./cilium/ks.yaml
  - ./hubble/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml