apiVersion: v1
kind: Secret
metadata:
    name: netbox-postgres-init-environment
    namespace: default
stringData:
    #ENC[AES256_GCM,data:mRmy1z3NFZ5SUdficE8=,iv:eX3Sc5lDNuOhHVSlRIMcUeP4e3MQnUEKA37q9fz66Yg=,tag:XrsKeTVuG9Bs7UHgfD62JQ==,type:comment]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BeFXBzUlN0YhU5QCyrvlQt4o3iHhDxUzBgqS/oPAYXiLpQ==,iv:KXeb0Cf2gNvmtZZV5phrufiRXL5ujb7j446htPWoJKo=,tag:zszn9sO3rPlxfqm4QI/s6g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:01t0RfXY6SXWkUzJP8faJQdlrauYH0K9oimORE5z,iv:sDs3wW9bdPkbAq+8ASqmepeJXDwPxQ6zzs6Gmw0PqAc=,tag:LUbvPdrGcC8dUj656Rcdyg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Z9X0AE4D,iv:mFp/jYkERrTfheZRODIeNHdINNNLrAKeWxN1FZ78CAI=,tag:f0uflg3kDzNYdv1wFAkJqg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:87PezSVV,iv:tSAUY/eUie0/VC+DXRuciYqkVuybw0GvO61F2XWAsGM=,tag:xsYiZC/YVnDNsdautXT2mw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:s0ppLdrVKGx1YTPhfuRNu/SfzZ3dcmmEBc27elxAVELxrUTXLi0PxYLaEF0aip4=,iv:u8uD+Ec1DzGDqSwvuW8lK271lTyX090nvUXKHgW/b2Y=,tag:AVcDp1CKK3IxJYE/khb9Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHIxalNFRXhqQm1PbVBa
            SC9IRWM5Yy96eVp4V3ZYYWE4NlhXR1dkcW5BClhqV3p6SGNxdlplN3liTXQ4dnFM
            NmFuUFNDanRNbk9DVy95YTZiMHBacFkKLS0tIDNvUHNnK2IrTGxPU2cyeHh3cGds
            YTJlVVFuQkJTYXlYZWczeDF2emZYSkUKb45FPw9TqqiUJFvC22G6gbwLxl+OSD8g
            6O1l7u5G8YJ1GH6EBuh2zWDVTy6xdrFQr/cVugoCRYPvAlX3lmFEFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T23:58:51Z"
    mac: ENC[AES256_GCM,data:Kl0cS3arEh0EgRHzDYrC32M53hqx6FrSIdbY6VXOq1dlewoVQjW5r+Jt9s5m79RiS8IDC+Bn66xCNxIt86Kw7f/+X46G7s/HNnX6QbwtAseSB4IWwadrKNbbYcofFOEQ04ojII43pxN03lhHuVonJ0H/qU49DmCedmigQ1Djp1Q=,iv:5V4bMrNgpvUQpKwifN5WjlwxB4gCtpSMM9dXJJpUbyw=,tag:2XbSmZurjZM1ihCy0isQPA==,type:str]
    pgp:
        - created_at: "2023-11-28T23:58:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAWrHR7EtDLbcctoW8XYCbcnwzMU2+PJFpHuuupEH1uV0w
            a9JACBrXWcNo7oxwAve54+wpefye6odYveIwtKY5rBiR0yErRZlvUCy8N08qkQuO
            0pMB5Kd3En7Vzknyj/RdZhqh4t0OuK+EouTUw5fQBu34910xYpFBLqiYWysaN6yO
            4xNmrRLJcGIz+BcDvjV0pYBRo6IfdhKZqGQ/IfTC13hQTIv/AifHukLvqv+uJX+f
            y5P9WfEEAZ7lQvzGkfv4ll13TUPIpt4Z0j5BKuUiOYBKH/0s0efUI5V/6fQWWPS7
            kkpL2Kg=
            =eEOe
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: netbox-redis-secrets
    namespace: default
stringData:
    redis_password: ENC[AES256_GCM,data:xCCvm6SdZbBEQsA7rcOeno6sG4A1dDW2mNiM,iv:m5xljbI1Jl5x3yzQ6fOSd/U8qi2aTsCNOzD5nzdE0go=,tag:kITlinGr40EI9pggXHEquQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHIxalNFRXhqQm1PbVBa
            SC9IRWM5Yy96eVp4V3ZYYWE4NlhXR1dkcW5BClhqV3p6SGNxdlplN3liTXQ4dnFM
            NmFuUFNDanRNbk9DVy95YTZiMHBacFkKLS0tIDNvUHNnK2IrTGxPU2cyeHh3cGds
            YTJlVVFuQkJTYXlYZWczeDF2emZYSkUKb45FPw9TqqiUJFvC22G6gbwLxl+OSD8g
            6O1l7u5G8YJ1GH6EBuh2zWDVTy6xdrFQr/cVugoCRYPvAlX3lmFEFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T23:58:51Z"
    mac: ENC[AES256_GCM,data:Kl0cS3arEh0EgRHzDYrC32M53hqx6FrSIdbY6VXOq1dlewoVQjW5r+Jt9s5m79RiS8IDC+Bn66xCNxIt86Kw7f/+X46G7s/HNnX6QbwtAseSB4IWwadrKNbbYcofFOEQ04ojII43pxN03lhHuVonJ0H/qU49DmCedmigQ1Djp1Q=,iv:5V4bMrNgpvUQpKwifN5WjlwxB4gCtpSMM9dXJJpUbyw=,tag:2XbSmZurjZM1ihCy0isQPA==,type:str]
    pgp:
        - created_at: "2023-11-28T23:58:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAWrHR7EtDLbcctoW8XYCbcnwzMU2+PJFpHuuupEH1uV0w
            a9JACBrXWcNo7oxwAve54+wpefye6odYveIwtKY5rBiR0yErRZlvUCy8N08qkQuO
            0pMB5Kd3En7Vzknyj/RdZhqh4t0OuK+EouTUw5fQBu34910xYpFBLqiYWysaN6yO
            4xNmrRLJcGIz+BcDvjV0pYBRo6IfdhKZqGQ/IfTC13hQTIv/AifHukLvqv+uJX+f
            y5P9WfEEAZ7lQvzGkfv4ll13TUPIpt4Z0j5BKuUiOYBKH/0s0efUI5V/6fQWWPS7
            kkpL2Kg=
            =eEOe
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: netbox-secrets
    namespace: default
type: Opaque
stringData:
    auth_ldap_bind_password: ENC[AES256_GCM,data:/AEf49YWZcbVnZL3C28=,iv:1s1zAZWxvYst1gCmxHz00pL3odPx/lgN07AnySLajoM=,tag:nwM4Er6obuq70L6t26eAvQ==,type:str]
    email_password: ENC[AES256_GCM,data:ruCNthDDePd23sdNCuY=,iv:+GeRbBPdc1eTrUpodbBOtHPSu0LGEN/+ozjMRwwoKYM=,tag:DHFefdL6ppFkd/TCxoVOPw==,type:str]
    napalm_password: ENC[AES256_GCM,data:maDv7RhfNURgnH53pQ8=,iv:U5yboCJx30UxTQgZRLV+JVUsA7nJVZPvteNyG2/xYqA=,tag:tpftwHGqNiCjaJVlUqYzsQ==,type:str]
    secret_key: ENC[AES256_GCM,data:ELuGZ49SJ0vdEndaAmw8tWnrHTfvRWpvFH8kvFfSGVOvRRAx2Yy/vYkavx5qp+clT8A=,iv:axLQ/JBrr6Y/Nap4ExS5ExM8sHehQN9U/9cqfEkD0WQ=,tag:fd31/Akv8YW0IC0oe9teqA==,type:str]
    superuser_password: ENC[AES256_GCM,data:JeNDrrKEmtKRBJjKOGSJOsQuaeUC6Ep1pvkEp5c60+4vTHMswg==,iv:sSbdsSofuk6M0gkbIR7zSTIq/4Gk3drlnArQCeV+ciU=,tag:iUBpak+A3b+N1urjLRbwOw==,type:str]
    superuser_api_token: ENC[AES256_GCM,data:JMJsHyPmHWIsG6d77efwzgrl+y4nb35uI+1OH8CGcV4wjOmvgajIhmeEv9UH3Lq0b6KEgi3L5P4=,iv:sYjcaSBKktHPPRlizcn7IFpArSJZjGJ5UbtLFJF9b3Q=,tag:dLAAG79yzoi90PXTh24/Nw==,type:str]
    postgres_password: ENC[AES256_GCM,data:/cGO3+fAz+YRy5ulu+yeZO7Epj21EAk+GtPfdcZG,iv:MVs5N5Wr1sxqDqkhdQPhVAUwgCXVb9DCyujUWn1lEDw=,tag:0odt0BajBD1cu7IexXOAMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHIxalNFRXhqQm1PbVBa
            SC9IRWM5Yy96eVp4V3ZYYWE4NlhXR1dkcW5BClhqV3p6SGNxdlplN3liTXQ4dnFM
            NmFuUFNDanRNbk9DVy95YTZiMHBacFkKLS0tIDNvUHNnK2IrTGxPU2cyeHh3cGds
            YTJlVVFuQkJTYXlYZWczeDF2emZYSkUKb45FPw9TqqiUJFvC22G6gbwLxl+OSD8g
            6O1l7u5G8YJ1GH6EBuh2zWDVTy6xdrFQr/cVugoCRYPvAlX3lmFEFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T23:58:51Z"
    mac: ENC[AES256_GCM,data:Kl0cS3arEh0EgRHzDYrC32M53hqx6FrSIdbY6VXOq1dlewoVQjW5r+Jt9s5m79RiS8IDC+Bn66xCNxIt86Kw7f/+X46G7s/HNnX6QbwtAseSB4IWwadrKNbbYcofFOEQ04ojII43pxN03lhHuVonJ0H/qU49DmCedmigQ1Djp1Q=,iv:5V4bMrNgpvUQpKwifN5WjlwxB4gCtpSMM9dXJJpUbyw=,tag:2XbSmZurjZM1ihCy0isQPA==,type:str]
    pgp:
        - created_at: "2023-11-28T23:58:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAWrHR7EtDLbcctoW8XYCbcnwzMU2+PJFpHuuupEH1uV0w
            a9JACBrXWcNo7oxwAve54+wpefye6odYveIwtKY5rBiR0yErRZlvUCy8N08qkQuO
            0pMB5Kd3En7Vzknyj/RdZhqh4t0OuK+EouTUw5fQBu34910xYpFBLqiYWysaN6yO
            4xNmrRLJcGIz+BcDvjV0pYBRo6IfdhKZqGQ/IfTC13hQTIv/AifHukLvqv+uJX+f
            y5P9WfEEAZ7lQvzGkfv4ll13TUPIpt4Z0j5BKuUiOYBKH/0s0efUI5V/6fQWWPS7
            kkpL2Kg=
            =eEOe
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
