---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: clabernetes
spec:
  interval: 5m
  ref:
    tag: 0.3.2
  url: oci://ghcr.io/srl-labs/clabernetes/clabernetes
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app clabernetes
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: clabernetes
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    globalConfig:
      naming: non-prefixed