---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app metrics-server
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/applications/kube-system/metrics-server/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
