---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: pod-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    DNSPolicy: ClusterFirst
    # -- Namespaces that might contain routed PODs and therefore
    # require a copy of the gneerated settings configmap.
    routed_namespaces:
      - default
    settings:
      VXLAN_ID: 43
      VPN_INTERFACE: "tun0"
      VPN_TRAFFIC_PORT: 2050
      VPN_BLOCK_OTHER_TRAFFIC: true
      NOT_ROUTED_TO_GATEWAY_CIDRS: &local_cidrs >-
        172.22.0.0/16 ${NET_POD_CIDR} ${NET_SVC_CIDR}
      VPN_LOCAL_CIDRS: *local_cidrs
    webhook:
      gatewayDefault: false
      gatewayAnnotation: vpn.home.arpa/tunnel
      gatewayAnnotationValue: ivpn
      gatewayLabel: vpn.home.arpa/tunnel
      gatewayLabelValue: ivpn
      namespaceSelector:
        type: custom
        custom:
          matchExpressions:
            - key: vpn.home.arpa/tunnel
              operator: In
              values: ['ivpn']
    service:
      vpn:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        #externalIPs: ["${SVC_POD_GATEWAY_ADDR}"]
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_POD_GATEWAY_ADDR}"
        ports:
          shadowsocks:
            enabled: true
            port: 8388
    addons:
      vpn:
        enabled: true
        type: gluetun
        networkPolicy:
          enabled: false
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.35.0@sha256:a98d1ec99e09a1b806aff7f0c3d8a133a8ede7d3d7a250b62029a39a61f01525
        env:
          - name: VPN_SERVICE_PROVIDER
            value: ivpn
          - name: VPN_TYPE
            value: openvpn
          - name: VPN_ENDPOINT_PORT
            value: 2050
          - name: FIREWALL
            value: "off"
          - name: SHADOWSOCKS
            value: "on"
          - name: DOT
            value: "off"
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: pod-gateway
                key: openvpn-username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pod-gateway
                key: openvpn-username
          - name: SERVER_COUNTRIES
            value: "Canada"
          - name: FIREWALL_VPN_INPUT_PORTS
            value: "42557"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      netshoot:
        enabled: true
