---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: pod-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    routed_namespaces:
      - default
    settings:
      VPN_TRAFFIC_PORT: 2050
      VPN_BLOCK_OTHER_TRAFFIC: true
    webhook:
      gatewayDefault: false
      gatewayAnnotation: vpn.home.arpa/ivpn
    addons:
      vpn:
        enabled: true
        type: gluetun
        networkPolicy:
          enabled: false
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.35.0@sha256:a98d1ec99e09a1b806aff7f0c3d8a133a8ede7d3d7a250b62029a39a61f01525
        env:
          - name: VPN_SERVICE_PROVIDER
            value: ivpn
          - name: VPN_TYPE
            value: openvpn
          - name: VPN_ENDPOINT_PORT
            value: 2050
          - name: FIREWALL
            value: "off"
          - name: SHADOWSOCKS
            value: "on"
          - name: DOT
            value: "off"
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: pod-gateway
                key: openvpn-username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pod-gateway
                key: openvpn-username
          - name: SERVER_COUNTRIES
            value: "Canada"
          - name: FIREWALL_VPN_INPUT_PORTS
            value: "42557"
        resources:
          requests:
            cpu: 5m
            memory: 64M
          limits:
            memory: 64M
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 10M