# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:XII6uiu9+22v/DqyT46sxIepyP+d2WK8gYhHvFpY,iv:+sTfzB0kvxwX0l0VQyeVcZ8jtVzQHhtckiXYUOSRyA8=,tag:ip/GMe1+KP3bcIrA7TrRFg==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:EM9ubyvXCA9uze1zz0jsbF6VSUZom901I+aYPSW3,iv:GbUn6kGvUzYpmNa7m2GdNnXpkRpq2WsATkiTLaJA+L4=,tag:KAtKbXHGIf2MCtiwQj61sQ==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jF0FE/SrqY+9G6BZpn/HcxYqDDj+ukgwnyF886+sPxuyy7BT/s6tZdedESe88gWB92ii1A08NU2x9LU9vMEJwlRNU9QknU7pVskPP09IBn6M6LSU6LWJ0Eo7zlKhNtDwLBrWKRjvY+wzJIvo5uG6sPs3FjG+WxZPCGwv2YN49/wCHq4=,iv:bkbyXweqGTs35A62XM0DHYrE6bJlFVKk4Rs1m07DYNM=,tag:0gWhDQowdApTkH/E1Sqlmw==,type:str]
    LDAP_SVCACCT_PASS: ENC[AES256_GCM,data:z4UkYPrVcX/bMNl+XJr0Va7xrK0sEFJyRIx+vqPn+SOve1KjP9SSGB8=,iv:KR0Ge1sXcCFmLhpbpz5xZvRm85W77rZvTRybFEqfoQA=,tag:CHHJFVTIGWjaHiowKLLyAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDVBMUlRUnNTdHRyeVRn
            c3pBV0RxUHBuVWhPQmI1dFRzTmxHdUlqSGlNClZXdE0wTVhKZm02WWJLb2hUaDdr
            SFNJdkd5dWlPYXVIMWZPQ0QzeTUrZ1kKLS0tIHlXbjQvVkdxdVZvNzl3Qmc3Y0xP
            eFdEKzdaaWJDbGJhRncxVVBPRi9CRm8K9LSpcHWKhiTAZM3kh5/Nd4jujy3rgpro
            l4a5zbG23nz7IbyhSLSbvuN/dGZ+H0qeQznXuIyP5SY4vlktPZNZeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T16:40:10Z"
    mac: ENC[AES256_GCM,data:8FreHTcJ6QXQAIjPYe8sFmvLoyHxkBnyq+IlaoCZY5tHAenHBwQw9ttWDeNiMOfHg8eidnHhfCeEd52gjOcEjUrK8rGuWmi/Bae8Xu6H/CgwbsnzUGVkWizhoZv9AbqKjgo7sIoqQ0eCaehwxom1Z1gA3BiXBQRkNIQpZ3EeRUE=,iv:CZUgUv0XRQbyqDvsyuGlkO5eii1oZ4DROhFO5078oLo=,tag:W7jQnGbdNRq0RzTa8wBIaw==,type:str]
    pgp:
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAE2HRX9E4+JzarXiGcraquQtwBMOK+qkyCiT76kvCHCgw
            GKcg1TlNY5I1Ce9Hq4irCJBmTIo2IbUE3NPHnhtrMx/kmB11A5VeqtwR4qArhPyP
            0pUBCpu2YyxZ3evVteneTCfOxu6gwpPIwf6DP30jwW4VOIz7xqL+6Tevgk4q5/ba
            aPou0R4F7jkneaKNKKHWj3xnTioaOdRY6J48BQ02qzae0y6/6E5akifU8mvjYrb2
            J44YGKkfrsr4436nmn99WZhsCsNwNqTDVBxvHseB3b0YP82SKY+RRD39so6hSMY4
            numyKnAd1g==
            =d4Mo
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        - created_at: "2024-08-10T16:40:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtU8CQcxKBkwSAQdAfANFHA2gM1P2tLPPonWN2GrfstrD7hGy9oa4G8w1aXIw
            5oIGZ/5403JCv+RW1UyVPE+pSOcLkcZT9UrYV3ezzp+R/Z5OcnlrvrplLWFJ0VHo
            0l4BwO2t9cbJPZyBjJW6i6jHx2dePIV8Qw70iKb/6pgK5W8IRZPymkTvc+LOfxsm
            pyvUlae3dVimqs2Kwf4gBsh4Rq9JerhlDWhsRVvIkvVlsigwoy2hTa082QiSfHv7
            =eKwW
            -----END PGP MESSAGE-----
          fp: 07EF252155A078987177E39C11A37ED357D49372
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
