apiVersion: v1
kind: Secret
metadata:
    name: vector-aggregator-secret
type: Opaque
stringData:
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:XBUtSdtZ,iv:bOactQpO+BXAq/d5zPBd1f250Z0RU0zGn++DF8aE+lw=,tag:TmLUIzxBN67PFepgCZTVpw==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:Cf5tNFoDuZ7hEJGblJBR96v1SiCqxqaJi+faoQqkRWxQAlY+OShoZg==,iv:BAAJtE7Kqu8jBWfbhf+p91hbkiH9C/mpSgANAl+EiCk=,tag:Da59gbVgo7pmtdbncUQjwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka0wxaHU1aWZZb21kcGtF
            bWFxWGkyMzBmMWZNRFUzbXJkdjMxdHhWZW5zCnlCTGJEbUtmcXM0VHo2QW51ZXM3
            aDQ5YUpOczFIbXgzVk03dXNuYVhDS0kKLS0tIGtCdkhIdU9UK0Q1WEpHSldnaDEv
            RTI4WUMyR1Y3b2lzamwrZVlISlF0ZUkK+yFjx4m8uL/7COFjQ/o5INKTTi2y66gq
            LSJlOPYMLt6gcpnu96ZQ57V/CFdwEyldwclK768W5wDder1vQrRWIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T14:47:19Z"
    mac: ENC[AES256_GCM,data:bCEyjHwk11Q9XIl5o48yJlug5VXvR3g5Rji9U/mcgCcPRzjwGZ8K5Ov5gl+zOR0phxWSW34FtUxv5Z01elIK58WYFkLI3guNEu6BDJOjhyAhxsT47lat1BerF0UvrHu+OVY24+W2BCBiW9rCMbL5C0CJm4hqUWRnXFYpfV6Cny0=,iv:Auuakr/CcVOJDxePMg66Rl6emC3st1KBzw9+sDU/OWE=,tag:m52bo+bh9fzles+yKMgf7g==,type:str]
    pgp:
        - created_at: "2024-02-29T14:47:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAXevcSA1HxDn4WGQEfX7c+k2L1SPCcXudhQuMKKD90RIw
            CfApwZ/laOptJPPmilZ+Y5/ilhV8zb3CLFzs+Wjigq66qo5mhVN7YOk/nyWpxObV
            0pYB3CfAOeVOXMnJtbWVn0s3RdC1b+t8sh8kgNHBhXaQyRu/UMUY/1hl3yQVRH6N
            fmnieE3QKXqTbU71GxtyM2jdpxMc+pBpNFEOVu81Spp0oGklEcnh/dWlYwVXq8OZ
            09BwOnW1m4ULNY6DxDwfDHHZY6jlwV/4YlUd6H2sFsfV/uogLDEa44OgJY1t1vTp
            0Xk9ELY0cfY=
            =xGyv
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
