version: "3"

tasks:

  kubeconfig:
    desc: Download kubeconfig from a remote k3s master node
    vars:
      MASTER_USERNAME: '{{.MASTER_USERNAME | default "elliana"}}'
      MASTER_HOST: '{{.MASTER_HOST | default "172.22.0.10"}}'
      KUBERNETES_API: '{{.KUBERNETES_API | default "172.22.0.1"}}'
    cmds:
      - rsync --verbose --progress --partial --rsync-path="sudo rsync" {{.MASTER_USERNAME}}@{{.MASTER_HOST}}:/etc/rancher/k3s/k3s.yaml "${KUBECONFIG}"
      - sed -i '' 's/127.0.0.1/{{.KUBERNETES_API}}/g' "${KUBECONFIG}"
      - chmod go-r "${KUBECONFIG}"

  clean-evicted:
    desc: Purge all pods marked as evicted
    cmds:
      - |
        kubectl get pods --all-namespaces -o json \
          | jq '.items[] | select(.status.reason!=null) | select(.status.reason | contains("Evicted")) | "kubectl delete pods \(.metadata.name) -n \(.metadata.namespace)"' \
          | xargs -n 1 bash -c