---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-operators-volsync
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-snapshot-controller
  path: ./kubernetes/operators/volsync/volsync/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: volsync
      namespace: volsync
  interval: 30m
  retryInterval: 1m
  timeout: 3m
