---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-cilium
  namespace: flux-system
spec:
  path: ./kubernetes/operators/kube-system/cilium/operator
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-cilium-configuration
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-cilium
  path: ./kubernetes/operators/kube-system/cilium/configuration
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-cilium-policy
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-operators-cilium
  path: ./kubernetes/operators/kube-system/cilium/policy
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
