---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-operators-external-dns-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/operators/external-dns/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-public
  wait: true
