---
- name: Copy kubeconfig to private directory
  run_once: true
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/../../.private/kubeconfig"
    flat: true
  when:
    - k3s_control_node is defined
    - k3s_control_node

- name: Replace API Server URL
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/../../.private/kubeconfig"
    regexp: "https://127.0.0.1:{{ k3s_server['https-listen-port'] }}"
    replace: "https://{{ k3s_registration_address }}:{{ k3s_server['https-listen-port'] }}"
